from manualkit import (Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table)

G="calendar-view"
MANUAL=Manual(control="CalendarView", package="com.dlsc.gemsfx", subtitle="A configurable month calendar with selection models", abstract="CalendarView displays a YearMonth as a six-row calendar grid with configurable header navigation, week numbers, date filtering, custom date cells and single, multiple or range selection.", cover_svg=f"{G}/cover.svg", cover_caption="CalendarView renders a full month with optional week numbers and selected dates.", chapters=[
Chapter("Introduction",[Para("<b>CalendarView</b> is the standalone month view used by CalendarPicker and DateRangeView. It is a focus-traversable Control whose skin builds a header, weekday row, date-cell grid and optional Today footer."),Section("Key features"),Bullets(["Shows a configurable <font face='Courier'>YearMonth</font> and marks today.","Header can show or hide month, year, arrows, dropdowns and a year spinner.","Selection model supports SINGLE_DATE, MULTIPLE_DATES and DATE_RANGE.","Optional week-number column and configurable week-number width.","Application-supplied DateCell factory and date filter.","Embedded YearMonthView and YearView for direct month / year selection."]),Section("Maven dependency"),Code("""<dependency>
    <groupId>com.dlsc.gemsfx</groupId>
    <artifactId>gemsfx</artifactId>
    <version>4.4.1</version>
</dependency>""", caption="CalendarView is in package <font face='Courier'>com.dlsc.gemsfx</font>.")]),
Chapter("Getting started",[Code("""CalendarView view = new CalendarView();
view.setYearMonth(YearMonth.now());
view.setShowTodayButton(true);
view.getSelectionModel().setSelectionMode(CalendarView.SelectionModel.SelectionMode.DATE_RANGE);
view.getSelectionModel().select(LocalDate.now());""", caption="A complete CalendarView setup."),Figure(f"{G}/cover.svg","A CalendarView with week numbers and selected dates."),Callout("The constructor sets <font face='Courier'>setMaxSize(Region.USE_PREF_SIZE, Region.USE_PREF_SIZE)</font>, so place it in a wrapper if it should grow beyond its preferred size.", kind="note")]),
Chapter("Anatomy",[Para("The skin uses two grid panes so weekday names and date cells stay aligned. It switches the stack pane front node between the normal date view, the month selection view and the year selection view."),Figure(f"{G}/anatomy.svg","The parts of a CalendarView."),Table(["Part","Style class","Description"],[["Root","calendar-view","Control with accessible role DATE_PICKER and localized role description 'calendar'."],["Header","header","Month/year labels, arrow buttons and optional year spinner."],["Weekday row","weekday-grid-pane, weekday-name","Localized day names starting with the locale's first day of week."],["Body grid","body-grid-pane","Six rows of DateCell nodes."],["Date cell","date-cell","Default cell text is day-of-month; created by cellFactory."],["Week number","week-number-label","Visible only when showWeekNumbers is true."],["Footer","footer, today-button","Visible only when showTodayButton is true."],["Selection overlays","selected, range-start, range-end, range-date","Style classes updated from SelectionModel."]], widths=[20,32,48])]),
Chapter("Control API",[Section("Displayed month and calendar data"),PropertyTable([Property("yearMonth","ObjectProperty&lt;YearMonth&gt;","YearMonth.now()","The month displayed by the control."),Property("today","ObjectProperty&lt;LocalDate&gt;","LocalDate.now()","Date treated as today; setToday rejects null."),Property("weekendDays","ObservableSet&lt;DayOfWeek&gt;","empty set","Days styled as weekend-day when present."),Property("earliestDate","ObjectProperty&lt;LocalDate&gt;","null","Lower selectable bound; also constrains inner YearMonthView / YearView."),Property("latestDate","ObjectProperty&lt;LocalDate&gt;","null","Upper selectable bound."),Property("dateFilter","ObjectProperty&lt;Callback&lt;LocalDate,Boolean&gt;&gt;","null","Disables cells for which the callback returns false.")]),Section("Header and visibility"),PropertyTable([Property("showMonth","BooleanProperty","true","Shows the month label and related month controls. Styleable."),Property("showYear","BooleanProperty","true","Shows the year label. Styleable."),Property("showMonthArrows","BooleanProperty","true","Shows previous / next month arrows. Styleable."),Property("showToday","BooleanProperty","true","Marks today with the today style class. Styleable."),Property("showTodayButton","BooleanProperty","false","Shows the footer button. Styleable."),Property("todayText","StringProperty","\"Today\"","Text of the Today button from ResourceBundleManager."),Property("headerLayout","ObjectProperty&lt;HeaderLayout&gt;","CENTER","CENTER, LEFT or RIGHT; not styleable.")]),Section("Selection and cells"),PropertyTable([Property("selectionModel","ObjectProperty&lt;SelectionModel&gt;","new SelectionModel()","Tracks selected dates."),Property("cellFactory","ObjectProperty&lt;Callback&lt;CalendarView,DateCell&gt;&gt;","view -> new DateCell()","Creates cells for the body grid."),Property("showWeekNumbers","BooleanProperty","false","Adds the week number column. Styleable."),Property("weekNumberColumnWidth","DoubleProperty","16","Width of the week-number column. Styleable."),Property("showDaysOfPreviousOrNextMonth","BooleanProperty","true","Shows padding days around the month. Styleable."),Property("markSelectedDaysOfPreviousOrNextMonth","BooleanProperty","true","Keeps adjacent-month selected days styled. Styleable.")])]),
Chapter("Header modes and embedded pickers",[Figure(f"{G}/modes.svg","CalendarView can switch from dates to month or year selection."),PropertyTable([Property("monthDisplayMode","ObjectProperty&lt;MonthDisplayMode&gt;","TEXT_ONLY","TEXT_ONLY or TEXT_AND_DROPDOWN. Styleable."),Property("yearDisplayMode","ObjectProperty&lt;YearDisplayMode&gt;","TEXT_ONLY","TEXT_ONLY, TEXT_AND_SPINNER or TEXT_AND_DROPDOWN. Styleable."),Property("monthSelectionViewEnabled","BooleanProperty","true","Allows clicking month label / dropdown to show YearMonthView. Styleable."),Property("yearSelectionViewEnabled","BooleanProperty","true","Allows clicking year label / dropdown to show YearView. Styleable."),Property("disablePreviousMonthButton","BooleanProperty","false","Disables previous month arrow. Styleable."),Property("disableNextMonthButton","BooleanProperty","false","Disables next month arrow. Styleable."),Property("disablePreviousYearButton","BooleanProperty","false","Disables previous year spinner arrow. Styleable."),Property("disableNextYearButton","BooleanProperty","false","Disables next year spinner arrow. Styleable."),Property("disableMonthDropdownButton","BooleanProperty","false","Disables month dropdown arrow. Styleable."),Property("disableYearDropdownButton","BooleanProperty","false","Disables year dropdown arrow. Styleable.")])]),
Chapter("Selection model",[Figure(f"{G}/selection.svg","The three selection modes style date cells differently."),Table(["Mode","State used","Click behaviour"],[["SINGLE_DATE","selectedDate","Click selects one date."],["MULTIPLE_DATES","selectedDates","Click toggles an individual date."],["DATE_RANGE","selectedDate + selectedEndDate","First click sets start; second click sets end; if end is before start, dates are swapped; clicking after a complete range clears first."]], widths=[24,31,45]),Code("""CalendarView.SelectionModel model = view.getSelectionModel();
model.setSelectionMode(CalendarView.SelectionModel.SelectionMode.MULTIPLE_DATES);
model.select(LocalDate.now());
model.select(LocalDate.now().plusDays(2));""")]),
Chapter("Styling",[Para("The stylesheet is <font face='Courier'>calendar-view.css</font>. It also recognizes root marker classes such as <font face='Courier'>popover</font> and <font face='Courier'>show-grid-lines</font>, although these are not pseudo classes."),Section("Style classes and pseudo classes"),Table(["Selector","Meaning"],[["<font face='Courier'>.calendar-view</font>","Root."],["<font face='Courier'>.container</font>","VBox containing header, weekday grid, body grid and footer."],["<font face='Courier'>.header</font>","Header row; pseudo classes :left, :center and :right reflect headerLayout."],["<font face='Courier'>.date-label</font>, <font face='Courier'>.month-label</font>, <font face='Courier'>.year-label</font>","Month and year labels."],["<font face='Courier'>.arrow-button</font>, <font face='Courier'>.previous-month-button</font>, <font face='Courier'>.next-month-button</font>","Month navigation."],["<font face='Courier'>.year-spinner</font>","Shown for TEXT_AND_SPINNER."],["<font face='Courier'>.weekday-grid-pane</font>, <font face='Courier'>.body-grid-pane</font>","The two grid panes."],["<font face='Courier'>.date-cell</font>","Cells; receive previous-month, next-month, weekend-day, today, selected, range-start, range-end, range-date."],["<font face='Courier'>.today-button</font>","Footer button." ]], widths=[55,45]),Section("Styleable CSS properties"),Table(["CSS property","Type","Default"],[["-fx-year-display-mode","YearDisplayMode","TEXT_ONLY"],["-fx-month-display-mode","MonthDisplayMode","TEXT_ONLY"],["-fx-show-today","boolean","true"],["-fx-show-week-numbers","boolean","false"],["-fx-disable-previous-month-button","boolean","false"],["-fx-disable-next-month-button","boolean","false"],["-fx-disable-next-year-button","boolean","false"],["-fx-disable-previous-year-button","boolean","false"],["-fx-disable-month-dropdown-button","boolean","false"],["-fx-disable-year-dropdown-button","boolean","false"],["-fx-month-selection-view-enabled","boolean","true"],["-fx-year-selection-view-enabled","boolean","true"],["-fx-show-month","boolean","true"],["-fx-show-year","boolean","true"],["-fx-show-today-button","boolean","false"],["-fx-show-month-arrows","boolean","true"],["-fx-mark-selected-days-of-previous-or-next-month","boolean","true"],["-fx-show-days-of-previous-or-next-month","boolean","true"],["-fx-week-number-column-width","size","16"]]),Code(""".calendar-view {
    -fx-show-week-numbers: true;
    -fx-month-display-mode: text-and-dropdown;
    -fx-year-display-mode: text-and-spinner;
}

.calendar-view > .stack-pane > .container > .body-grid-pane > .date-cell.range-date {
    -fx-background: derive(-fx-accent, +80%);
}""")]),
Chapter("Localization",[Para("CalendarView uses ResourceBundleManager with bundle type CALENDAR_VIEW."),Table(["Key","English default"],[["button.today","Today"],["accessible.role-description","calendar"]], widths=[42,58])]),
Chapter("Accessibility",[Para("CalendarView sets <font face='Courier'>AccessibleRole.DATE_PICKER</font> with localized role description <font face='Courier'>calendar</font>. It requests focus on mouse or touch press and is focus traversable by default.")]),
Chapter("Recipes",[Section("Week-number calendar"),Code("""view.setShowWeekNumbers(true);
view.setWeekNumberColumnWidth(22);"""),Section("Business-day picker"),Code("""view.getWeekendDays().setAll(DayOfWeek.SATURDAY, DayOfWeek.SUNDAY);
view.setDateFilter(date -> !view.getWeekendDays().contains(date.getDayOfWeek()));"""),Section("Custom cells"),Code("""view.setCellFactory(calendar -> new CalendarView.DateCell() {
    @Override public void updateItem(LocalDate date, boolean empty) {
        super.updateItem(date, empty);
        if (date != null && busyDates.contains(date)) {
            getStyleClass().add("busy");
        }
    }
});"""),Section("Jump to today"),Code("""view.setToday(LocalDate.now());
view.setShowTodayButton(true);"""),Section("Checklist"),Numbered(["Choose the selection mode before processing selected properties.","Use earliestDate/latestDate for hard bounds.","Use dateFilter for dynamic business rules.","Keep custom DateCell implementations small and update style classes when the item changes."])]),
Chapter("See also",[Bullets(["Demo application: <font face='Courier'>com.dlsc.gemsfx.demo.CalendarViewApp</font> (run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.CalendarViewApp</font>)","Related controls: <font face='Courier'>CalendarPicker</font>, <font face='Courier'>DateRangeView</font>, <font face='Courier'>YearMonthPicker</font>, <font face='Courier'>YearView</font>.","API documentation: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/"])])])
