from manualkit import (Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table)

G="day-of-week-picker"
MANUAL=Manual(control="DayOfWeekPicker", package="com.dlsc.gemsfx", subtitle="A SelectionBox specialized for localized weekdays", abstract="DayOfWeekPicker is a SelectionBox of DayOfWeek values. It orders days by locale, supports single and multiple selection, and adds quick buttons for clear, today, all days, weekdays and weekends.", cover_svg=f"{G}/cover.svg", cover_caption="DayOfWeekPicker summarizes weekday selections and opens a SelectionBox popup.", chapters=[
Chapter("Introduction",[Para("<b>DayOfWeekPicker</b> extends <font face='Courier'>SelectionBox&lt;DayOfWeek&gt;</font>. It inherits the SelectionBox popup and selection model, then replaces the items and quick buttons with weekday-specific behaviour."),Section("Key features"),Bullets(["Items are the seven DayOfWeek values ordered by the locale's first day of week.","Single mode shows Clear and Today buttons.","Multiple mode shows Clear, All Days, Weekdays and Weekends buttons.","Display summaries include All Days, Weekdays, Weekends and consecutive ranges such as Mon ~ Wed.","Weekend days are computed from WeekFields of the current locale."]),Section("Maven dependency"),Code("""<dependency>
    <groupId>com.dlsc.gemsfx</groupId>
    <artifactId>gemsfx</artifactId>
    <version>4.4.1</version>
</dependency>""", caption="DayOfWeekPicker is in package <font face='Courier'>com.dlsc.gemsfx</font>.")]),
Chapter("Getting started",[Code("""DayOfWeekPicker picker = new DayOfWeekPicker();
picker.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);
picker.getSelectionModel().select(DayOfWeek.MONDAY);
picker.getSelectionModel().select(DayOfWeek.FRIDAY);

picker.getSelectionModel().getSelectedItems().addListener((ListChangeListener<DayOfWeek>) change -> {
    System.out.println(picker.getSelectionModel().getSelectedItems());
});""", caption="A complete DayOfWeekPicker setup."),Figure(f"{G}/cover.svg","DayOfWeekPicker in a schedule filter."),Callout("Selection mode is changed on the inherited <font face='Courier'>MultipleSelectionModel</font>: <font face='Courier'>picker.getSelectionModel().setSelectionMode(...)</font>.", kind="tip")]),
Chapter("Anatomy",[Figure(f"{G}/anatomy.svg","The parts inherited from SelectionBox plus DayOfWeekPicker additions."),Table(["Part","Style class","Description"],[["Root","combo-box-base, combo-box, selection-box, day-of-week-picker","DayOfWeekPicker adds its own root class after SelectionBox construction."],["Display label","display-label","Shows selectedItemsConverter text or promptText."],["Arrow","arrow-button, arrow","Shows the popup unless readOnly."],["Popup","selection-popup","PopupControl with autoFix, autoHide and hideOnEscape."],["Extra buttons","extra-buttons-box, extra-button","Day-specific button set installed at the top."],["Items","item, single-item / multiple-item","Radio buttons in SINGLE mode, check boxes in MULTIPLE mode."],["Quick buttons","clear-button, today-button, select-all-button, weekdays-button, weekends-button","Visibility depends on selection mode."]], widths=[25,35,40])]),
Chapter("Control API",[Section("DayOfWeekPicker methods"),PropertyTable([Property("getLocalizedDayOrder()","List&lt;DayOfWeek&gt;","locale dependent","Returns seven days starting with WeekFields.of(Locale.getDefault()).getFirstDayOfWeek()."),Property("getWeekendDays()","List&lt;DayOfWeek&gt;","locale dependent","Returns two weekend days computed from the locale first day plus five and six days."),Property("getWeekdays()","List&lt;DayOfWeek&gt;","locale dependent","All DayOfWeek values except getWeekendDays()."),Property("isSelectedAll()","boolean","derived","True when selected item count equals item count."),Property("isOnlyWeekdaysSelected()","boolean","derived","True when the selected set equals getWeekdays()."),Property("isOnlyWeekendsSelected()","boolean","derived","True when the selected set equals getWeekendDays().")]),Section("Inherited SelectionBox properties"),PropertyTable([Property("items","ListProperty&lt;DayOfWeek&gt;","localized weekdays","Choice list, initialized by the constructor."),Property("selectionModel","ObjectProperty&lt;MultipleSelectionModel&lt;DayOfWeek&gt;&gt;","CustomMultipleSelectionModel","Supports SelectionMode.SINGLE and SelectionMode.MULTIPLE."),Property("promptText","StringProperty","null","Shown when no item is selected."),Property("autoHideOnSelection","BooleanProperty","true","Controls popup hiding for item/extra-button interactions."),Property("selectedItemsConverter","ObjectProperty&lt;StringConverter&lt;List&lt;DayOfWeek&gt;&gt;&gt;","weekday summary converter","Formats the display label."),Property("itemConverter","ObjectProperty&lt;StringConverter&lt;DayOfWeek&gt;&gt;","full localized day name","Formats popup items."),Property("readOnly","BooleanProperty","false","Styleable; hides the arrow and prevents opening."),Property("animationEnabled","BooleanProperty","false","Styleable fade transitions for popup show/hide.")])]),
Chapter("Selection modes and quick buttons",[Figure(f"{G}/modes.svg","Single and multiple modes expose different quick buttons."),Table(["Mode","Popup controls","Selection summary"],[["SINGLE","Radio buttons, Clear and Today","Full localized day name."],["MULTIPLE","Check boxes, Clear, All Days, Weekdays, Weekends","Special summaries or consecutive ranges." ]], widths=[25,38,37]),Code("""picker.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);

// Built-in quick button logic can also be called directly:
picker.getSelectionModel().clearSelection();
for (DayOfWeek day : picker.getWeekdays()) {
    picker.getSelectionModel().select(day);
}""")]),
Chapter("Summaries and locale ordering",[Figure(f"{G}/summaries.svg","The selected-items converter chooses compact weekday summaries."),Para("When several individual days are selected, the converter sorts them by localized day order, merges consecutive runs and renders each run with short localized day names joined by <font face='Courier'> ~ </font>. Non-consecutive runs are separated by commas."),Code("""List<DayOfWeek> order = picker.getLocalizedDayOrder();
List<DayOfWeek> weekends = picker.getWeekendDays();""")]),
Chapter("Styling",[Section("Style classes and pseudo classes"),Table(["Selector","Meaning"],[[".day-of-week-picker","Root class added by DayOfWeekPicker."],[".selection-box","Inherited root class and stylesheet."],[".display-label","Text shown on the closed picker."],[".arrow-button > .arrow","Popup arrow."],[".selection-popup > .content","Popup content pane."],[".extra-buttons-box .extra-button","Quick selection buttons."],[".clear-button, .today-button, .select-all-button, .weekdays-button, .weekends-button","Specific quick buttons."],[".item, .single-item, .multiple-item","Popup radio buttons / check boxes."],[":readonly, :empty, :showing, :single, :multiple","Pseudo classes set by SelectionBoxSkin."]], widths=[52,48]),Section("Styleable CSS properties"),Table(["CSS property","Type","Default"],[["-fx-read-only","boolean","false"],["-fx-animation-enabled","boolean","false"]]),Code(""".day-of-week-picker {
    -fx-read-only: false;
    -fx-animation-enabled: true;
}

.selection-popup > .content .extra-buttons-box .weekdays-button {
    -fx-font-weight: bold;
}""")]),
Chapter("Localization",[Table(["Key","English default"],[["summary.all-days","All Days"],["summary.weekdays","Weekdays"],["summary.weekends","Weekends"],["action.clear","Clear"],["action.today","Today"],["action.all-days","All Days"],["action.weekdays","Weekdays"],["action.weekends","Weekends"]], widths=[45,55])]),
Chapter("Accessibility",[Para("SelectionBox already sets <font face='Courier'>AccessibleRole.COMBO_BOX</font> and binds accessible text to the same selection summary shown in the display label. DayOfWeekPicker also calls setRole with COMBO_BOX, keeping the same role.")]),
Chapter("Recipes",[Section("Single-day picker"),Code("picker.getSelectionModel().setSelectionMode(SelectionMode.SINGLE);") ,Section("Weekday filter"),Code("""picker.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);
for (DayOfWeek day : picker.getWeekdays()) {
    picker.getSelectionModel().select(day);
}"""),Section("Keep popup open"),Code("picker.setAutoHideOnSelection(false);") ,Section("Custom empty text"),Code("picker.setPromptText(\"Any day\");"),Section("Checklist"),Numbered(["Use getLocalizedDayOrder() when showing external labels beside the picker.","Use selection mode MULTIPLE before calling selectAll().","Do not replace items unless you intentionally leave the weekday-specific domain.","Use readOnly instead of disabled when the value should remain readable but not editable."])]),
Chapter("See also",[Bullets(["Demo application: <font face='Courier'>com.dlsc.gemsfx.demo.DayOfWeekPickerApp</font> (run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.DayOfWeekPickerApp</font>)","Related controls: <font face='Courier'>SelectionBox</font>, <font face='Courier'>CalendarView</font>, <font face='Courier'>DateRangePicker</font>.","API documentation: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/"])])])
