from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table

G = "dialog-pane"

MANUAL = Manual(
    control="DialogPane",
    package="com.dlsc.gemsfx",
    subtitle="In-window dialogs with glass-pane blocking and typed helper APIs",
    abstract='DialogPane is a StackPane overlay for lightweight application dialogs. It manages a glass pane, one or more Dialog models, typed helper methods, custom content, validation, resizing, button bars, blocking and animation.',
    cover_svg=f"{G}/cover.svg",
    cover_caption='DialogPane shows typed dialogs above application content while a glass pane blocks the background.',
    chapters=[
        Chapter('Introduction', [Para('<b>DialogPane</b> is a StackPane that should cover the application area. It stays unmanaged and invisible while no dialogs are active, then displays a glass pane and one or more animated dialog content panes.'), Section('Key features'), Bullets(['Typed helpers for information, warning, confirmation, error, text input, custom node and busy dialogs.', 'Dialog models with title, content, value, validation, button types and close callbacks.', 'Global glass pane plus nested blocking glass panes for older dialogs.', 'Default header and footer factories, both replaceable.', 'OS-specific ButtonBar ordering and button validation rules.', 'Resizable dialogs with optional Preferences persistence.', 'ESC cancels the top dialog; SHIFT+ESC hides all dialogs.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="GemsFX controls live in module <font face='Courier'>com.dlsc.gemsfx</font>.")]),
        Chapter('Getting started', [Code('StackPane root = new StackPane(applicationContent);\nDialogPane dialogs = new DialogPane();\nroot.getChildren().add(dialogs);\n\ndialogs.showInformation("Saved", "The document has been saved.");\n\ndialogs.showConfirmation("Delete", "Really delete this item?")\n       .onClose(button -> {\n           if (button == ButtonType.YES) {\n               deleteItem();\n           }\n       });', caption='Create the pane as the last child of a StackPane and use helper methods.'), Figure(f"{G}/cover.svg", 'A dialog is centered over the application while the glass pane blocks input.')]),
        Chapter('Anatomy', [Para('Each active Dialog is represented by a ContentPane. The newest dialog is interactive; older dialogs receive a nested glass pane and become blocked.'), Figure(f"{G}/anatomy.svg", 'The layers and default parts of DialogPane.'), Table(['Part', 'Style class', 'Description'], [['.dialog-pane', 'Root StackPane; transparent, fills available area.'], ['.glass-pane', 'Global glass pane over application content.'], ['.content-pane', 'Per-dialog shell; receives type style classes.'], ['.information, .warning, .error, .confirmation, .input, .blank', 'Dialog type classes.'], ['.vbox', 'Header/content/footer column.'], ['.header, .title-and-icon-box, .title, .icon, .close-button', 'Default DialogHeader parts.'], ['.content, .padding, .message-label, .prompt-node-wrapper', 'Content wrappers and message labels.'], ['.button-bar, .footer', 'Default DialogButtonBar footer.']])]),
        Chapter('Pane API', [Section('Factories, dialogs and animation'), PropertyTable([Property('headerFactory','ObjectProperty&lt;Callback&lt;Dialog&lt;?&gt;, Node&gt;&gt;','DialogHeader::new','Factory for the default title and close-button area.'), Property('footerFactory','ObjectProperty&lt;Callback&lt;Dialog&lt;?&gt;, Node&gt;&gt;','DialogButtonBar::new','Factory for the default ButtonBar footer.'), Property('dialogs','ListProperty&lt;Dialog&lt;?&gt;&gt;','empty list','Currently active dialogs. Adding and removing drives animations.'), Property('animationDuration','ObjectProperty&lt;Duration&gt;','100 ms','Duration for dialog fly-in/fly-out and glass pane fade.'), Property('animateDialogs','BooleanProperty','true','Enables the fly-in/fly-out transition.'), Property('fadeInOut','BooleanProperty','true','Animates dialog and glass-pane opacity.'), Property('showingDialog','ReadOnlyBooleanProperty','false','True while dialogs is not empty.'), Property('maximizedPadding','DoubleProperty','20','Insets kept around maximized dialogs.'), Property('labelSupplier','ObjectProperty&lt;Supplier&lt;Label&gt;&gt;','Label::new','Supplier for message labels in standard dialogs.'), Property('sendButtonText','StringProperty','Send','Text for the optional send button in detailed error dialogs.'), Property('converter','ObjectProperty&lt;StringConverter&lt;ButtonType&gt;&gt;','buttonType.getText()','Converts ButtonType text for footer buttons.')])]),
        Chapter('Dialog model API', [PropertyTable([Property('id','StringProperty','null','Optional application identifier.'), Property('preferences','ObjectProperty&lt;Preferences&gt;','null','Stores/restores width and height through DefaultResizeHandler.'), Property('pref/min/max width and height','DoubleProperty','USE_COMPUTED_SIZE','Size constraints mirrored to the ContentPane.'), Property('required','BooleanProperty','false','Adds required-text validation for text input dialogs.'), Property('showCloseButton','BooleanProperty','true','Observed by the default header close button.'), Property('delay','ObjectProperty&lt;Duration&gt;','null','Optional delay before the dialog is added to the pane.'), Property('usingPadding','BooleanProperty','true; BLANK sets false','Adds the padding style class around content.'), Property('contentAlignment','ObjectProperty&lt;Pos&gt;','CENTER_LEFT','Alignment of the content node in the content area.'), Property('value','ObjectProperty&lt;T&gt;','null','Value produced by input/custom dialogs.'), Property('valid','BooleanProperty','true','Disables validating default buttons when false.')]), PropertyTable([Property('buttonTypes','ObservableList&lt;ButtonType&gt;','depends on Type','Footer button definitions.'), Property('sameWidthButtons','BooleanProperty','true','Uses ButtonBar uniform-size buttons.'), Property('maximize','BooleanProperty','false','Uses all available pane area minus maximizedPadding.'), Property('content','ObjectProperty&lt;Node&gt;','null','Main content node.'), Property('extras','ObjectProperty&lt;Node&gt;','null','Optional node for custom header/footer factories.'), Property('title','StringProperty','Dialog','Title used by DialogHeader.'), Property('showHeader / showFooter','BooleanProperty','true / true','Controls default header and footer visibility.'), Property('validator','ObjectProperty&lt;Validator&gt;','new Validator()','ValidatorFX validator run by committing buttons.'), Property('resizable','BooleanProperty','false','Installs ResizingBehaviour when true.'), Property('onResize','ObjectProperty&lt;BiConsumer&gt;','DefaultResizeHandler','Receives new size; default persists to Preferences.')])]),
        Chapter('Dialog types and helper methods', [Para('The Type enum contains INPUT, INFORMATION, ERROR, WARNING, CONFIRMATION and BLANK. The constructor selects default buttons: input and warning use OK/CANCEL, information and error use OK, confirmation uses YES/NO, and blank dialogs have no standard padding.'), Figure(f"{G}/types.svg", 'Built-in dialog types and their default presentation.'), Bullets(['showError supports message-only, exception-details, text details and optional send action.', 'showTextInput chooses TextField or ResizableTextArea and binds dialog.value to text.', 'showNode accepts any Node, maximize, custom buttons, same-width buttons and an optional validity property.', 'showBusyIndicator creates a delayed blank busy dialog with no buttons.'])]),
        Chapter('Lifecycle, buttons and validation', [Figure(f"{G}/lifecycle.svg", 'Dialog lifecycle from helper method to close callback.'), Para("Calling <font face='Courier'>show()</font> or a helper adds the dialog immediately, unless delay is set. Pressing a validating button runs the ValidatorFX validator; invalid input keeps the dialog open. CANCEL calls cancel(), clears value and commits ButtonType.CANCEL."), Callout("The current source exposes <font face='Courier'>Dialog&lt;T&gt;</font> and <font face='Courier'>onClose</font> callbacks. It does not expose a Future or CompletionStage result API.", kind='note')]),
        Chapter('Blocking, keyboard and focus', [Figure(f"{G}/stacking.svg", 'Multiple dialogs stack; only the top dialog is active.'), Bullets(['ESC cancels the most recently opened dialog.', 'SHIFT+ESC calls hideAllDialogs().', 'Input dialogs attempt to keep focus inside the dialog content.', 'A double-click in ListView content fires the default button when one exists.'])]),
        Chapter('Customization recipes', [Section('Custom content'), Code('DialogPane.Dialog<Object> dialog = dialogs.showNode(DialogPane.Type.INFORMATION,\n        "Select item", tableView, true, List.of(ButtonType.OK, ButtonType.CANCEL));\ndialog.setResizable(true);', caption=None), Section('Persist size'), Code('dialog.setId("preferences.dialog");\ndialog.setPreferences(Preferences.userNodeForPackage(App.class).node(dialog.getId()));\ndialog.setResizable(true);', caption=None), Section('Uppercase buttons'), Code('dialogs.setConverter(new StringConverter<>() {\n    public String toString(ButtonType type) { return type == null ? "" : type.getText().toUpperCase(); }\n    public ButtonType fromString(String text) { return null; }\n});', caption=None)]),
        Chapter('Styling', [Table(['Style class', 'Description'], [['.dialog-pane', 'Root StackPane; transparent, fills available area.'], ['.glass-pane', 'Global glass pane over application content.'], ['.content-pane', 'Per-dialog shell; receives type style classes.'], ['.information, .warning, .error, .confirmation, .input, .blank', 'Dialog type classes.'], ['.vbox', 'Header/content/footer column.'], ['.header, .title-and-icon-box, .title, .icon, .close-button', 'Default DialogHeader parts.'], ['.content, .padding, .message-label, .prompt-node-wrapper', 'Content wrappers and message labels.'], ['.button-bar, .footer', 'Default DialogButtonBar footer.'], ['.error-container, .error-text-area', 'Detailed error-dialog content.'], ['.busy-dialog, .dialog-pane-busy-indicator, .circular-progress', 'Busy indicator dialog classes.']]), Code('.dialog-pane > .content-pane {\n    -fx-background-radius: 8px;\n}\n.dialog-pane > .content-pane > .vbox > .button-bar {\n    -fx-alignment: center-right;\n}\n.dialog-pane > .content-pane.error .message-label {\n    -fx-font-weight: bold;\n}', caption='Example CSS for DialogPane.'), Para('DialogPane has no custom styleable CSS properties; styling is through ordinary style classes in dialog-pane.css.')]),
        Chapter('Localization', [Table(['Key', 'English default'], [['button.send', 'Send'], ['title.default', 'Dialog'], ['header.title.fallback', 'Dialog']])]),
        Chapter('Recipes', [Section('Disable animation'), Code('dialogs.setAnimateDialogs(false);\ndialogs.setFadeInOut(false);', caption=None), Section('Maximized dialog'), Code('Dialog<Object> dialog = new Dialog<>(dialogs, DialogPane.Type.INFORMATION);\ndialog.setTitle("Details");\ndialog.setContent(detailsNode);\ndialog.setMaximize(true);\ndialog.show();', caption=None), Section('Required text'), Code('Dialog<String> dialog = dialogs.showTextInput("Name", "Required", "", false);\ndialog.setRequired(true);', caption=None), Section('Checklist'), Numbered(['Add DialogPane last so it covers the scene.', 'Use showNode for custom UI and typed helpers for standard cases.', 'Keep long operations outside the JavaFX application thread.', 'Set preferences only for dialogs whose size should persist.'])]),
        Chapter('See also', [Bullets(["Demo app: <font face='Courier'>DialogPaneApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.DialogPaneApp</font>.", 'Related controls: GlassPane, ResizableTextArea and CircularProgressIndicator usage inside the dialog pane.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
