from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, PageBreak, Para, Property, PropertyTable, Section, Table

G = "enhanced-label"

MANUAL = Manual(
    control="EnhancedLabel",
    package="com.dlsc.gemsfx",
    subtitle="A selectable, copyable Label",
    abstract='EnhancedLabel extends JavaFX Label with whole-label selection and clipboard copying. Double-click selects the label, shortcut+C copies the configured content supplier, and the context menu exposes a localized copy action.',
    cover_svg=f"{G}/cover.svg",
    cover_caption='EnhancedLabel makes ordinary labels selectable and copyable.',
    chapters=[
        Chapter('Introduction', [Para('<b>EnhancedLabel</b> is a Label subclass. It keeps normal Label text/graphic APIs and adds selection, copy shortcut, context-menu copying and a supplier for custom clipboard content.'), Section('Key features'), Bullets(['Double-click selects the entire label.', 'Shortcut+C copies while the label has focus.', 'Context-menu request selects the label and shows a copy item.', 'copyContentSupplier can copy a different value than displayed text.', 'onCopyAction can replace the default copy behaviour.', 'Losing focus clears selected state.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="GemsFX controls live in module <font face='Courier'>com.dlsc.gemsfx</font>.")]),
        Chapter('Getting started', [Code('EnhancedLabel label = new EnhancedLabel("Customer account #12345678");\nlabel.setCopyContentSupplier(() -> "12345678");\nlabel.setCopyMenuItemText("Copy ID");', caption='A label that displays a sentence but copies only the ID.'), Figure(f"{G}/cover.svg", 'EnhancedLabel selected and unselected examples.')]),
        Chapter('Anatomy', [Figure(f"{G}/anatomy.svg", 'The properties and hooks added by EnhancedLabel.'), Table(['Part', 'Description'], [['Label base class', 'All normal Label text and graphic properties remain available.'], ['selected property', 'Whole-label selection state.'], ['ContextMenu', 'Contains one copy MenuItem.'], ['copyContentSupplier', 'Defines clipboard content.'], ['onCopyAction', 'Allows custom copy handling.']])]),
        Chapter('Control API', [PropertyTable([Property('selected','BooleanProperty','false','True when the whole label is selected; drives :selected pseudo class.'), Property('copyMenuItemText','StringProperty','Copy text','Text of the context-menu item.'), Property('copyContentSupplier','ObjectProperty&lt;Supplier&lt;String&gt;&gt;','this::getText','String placed on the clipboard by default copy action.'), Property('onCopyAction','ObjectProperty&lt;EventHandler&lt;ActionEvent&gt;&gt;','copyText handler','Action invoked by the context-menu item; default copies supplier content.')])]),
        Chapter('Interaction behaviour', [Figure(f"{G}/interactions.svg", 'Double-click selection and focus clearing.'), Bullets(['The control is focus traversable.', 'Double-click with primary mouse button sets selected true.', 'When selected and not focused, it requests focus.', 'When focus is lost, selected becomes false.', 'Context-menu request also sets selected true.'])]),
        Chapter('Clipboard flow', [Figure(f"{G}/clipboard.svg", 'Copy shortcut, menu action and supplier flow.'), Para('The default copy action writes copyContentSupplier.get() to the system clipboard. Set onCopyAction to intercept or replace that behaviour.')]),
        Chapter('Styling', [Figure(f"{G}/styling.svg", 'The selected pseudo class is the main styling hook.'), Table(['Style class / pseudo class', 'Description'], [['.enhanced-label', 'Root style class added by init().'], [':selected', 'Pseudo class when selected is true; CSS uses accent background and white text.']]), Code('.enhanced-label:selected {\n    -fx-background-color: -fx-accent;\n    -fx-text-fill: white;\n}', caption='Default selected styling from enhanced-label.css.')]),
        Chapter('Localization', [Table(['Key', 'English default'], [['context.copy-text', 'Copy text']])]),
        Chapter('Accessibility', [Para("EnhancedLabel sets <font face='Courier'>AccessibleRole.TEXT</font>. It inherits Label text semantics and adds keyboard copy support.")]),
        Chapter('Recipes', [PageBreak(), Section('Copy hidden identifier'), Code('label.setCopyContentSupplier(() -> customer.getId());\nlabel.setCopyMenuItemText("Copy customer ID");', caption=None), Section('Observe selection'), Code('toggle.selectedProperty().bindBidirectional(label.selectedProperty());', caption=None), Section('Custom copy action'), Code('label.setOnCopyAction(evt -> {\n    logCopy(label.getText());\n    evt.consume();\n});', caption=None), Section('Checklist'), Numbered(['Use EnhancedLabel when the whole label is copied as one unit.', 'Use TextView for arbitrary range selection inside multiline text.', 'Set a supplier when displayed text differs from clipboard text.', 'Keep selected styling accessible against the accent color.'])]),
        Chapter('See also', [PageBreak(), Bullets(["Demo app: <font face='Courier'>EnhancedLabelApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.EnhancedLabelApp</font>.", 'Related control: TextView for range-based text selection.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
