from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table

G = "filter-view"

MANUAL = Manual(
    control="FilterView",
    package="com.dlsc.gemsfx",
    subtitle="Grouped predicate filters with chips and a search field",
    abstract='FilterView is a generic filtering control. It groups selectable Predicate objects into menu buttons, turns selections into chips, optionally combines them with a text-filter provider, and exposes a read-only filteredItems list for tables, lists or custom views.',
    cover_svg=f"{G}/cover.svg",
    cover_caption="FilterView combines group menus, chips and a search field into a reusable predicate pipeline.",
    chapters=[
        Chapter('Introduction', [Para("<b>FilterView</b> is a <font face='Courier'>Control</font> for building reusable filter bars. It owns source items, selected filters and a read-only filteredItems list."), Section('Key features'), Bullets(['Filter groups shown as menu buttons with All and None actions.', 'Filters in the same group are ORed; different groups are ANDed.', 'Optional text filter from a SearchTextField.', 'Optional additional predicate for application state.', 'Selected filters and filter text become removable chips.', 'Header with title, subtitle, graphics and extras.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="The class is in <font face='Courier'>com.dlsc.gemsfx</font>.")]),
        Chapter('Getting started', [Code('FilterView<Person> filterView = new FilterView<>();\nfilterView.setTitle("People");\nfilterView.setTextFilterProvider(text -> person ->\n    person.getFirstName().toLowerCase().contains(text.toLowerCase()) ||\n    person.getLastName().toLowerCase().contains(text.toLowerCase()));\n\nFilterGroup<Person> role = new FilterGroup<>("Role");\nrole.getFilters().add(new Filter<>("Parents") {\n    @Override public boolean test(Person p) { return p.getRole().equals("Parent"); }\n});\nfilterView.getFilterGroups().add(role);\ntable.setItems(new SortedList<>(filterView.getFilteredItems()));', caption='A filter view feeding a table.'), Figure(f"{G}/cover.svg", 'FilterView above a table of filtered items.')]),
        Chapter('Anatomy', [Figure(f"{G}/anatomy.svg", 'The parts of FilterView.'), Table(['Part', 'Style class', 'Description'], [['.filter-view', 'Root control style class.'], ['.filter-container', 'Main container in the skin.'], ['.header-box', 'Title, subtitle, search field and extras.'], ['.title-subtitle-box, .title-box, .title, .title-postfix, .subtitle', 'Header text containers and labels.'], ['.filter-groups', 'Container for group menu buttons.'], ['.filters', 'Container for selected filter chips.'], ['.clear-filter-label', 'Action label that clears text and selected filters.']])]),
        Chapter('Control API', [Section('Filtering properties'), PropertyTable([Property('items', 'ListProperty&lt;T&gt;', 'empty list', 'Source items to filter.'), Property('filteredItems', 'ReadOnlyListProperty&lt;T&gt;', 'FilteredList over items', 'Result list after all predicates are applied.'), Property('filterGroups', 'ListProperty&lt;FilterGroup&lt;T&gt;&gt;', 'empty list', 'Groups shown as menu buttons.'), Property('filters', 'ReadOnlyListProperty&lt;Filter&lt;T&gt;&gt;', 'flattened groups', 'All filters from all groups.'), Property('filterText', 'StringProperty', 'empty string', 'Text in the SearchTextField.'), Property('textFilterProvider', 'ObjectProperty&lt;Function&lt;String, Predicate&lt;T&gt;&gt;&gt;', 'null', 'Creates a predicate from filterText. Applied only when text is not blank.'), Property('additionalFilterPredicate', 'ObjectProperty&lt;Predicate&lt;T&gt;&gt;', 'item -> true', 'Extra predicate ANDed with all other filters.'), Property('scrollThreshold', 'IntegerProperty', '100', 'Selected filter count above which chips are wrapped in a ScrollPane.')], caption=None), Section('Header properties'), PropertyTable([Property('showHeader', 'BooleanProperty', 'true', 'Shows title, subtitle, search and extras header. Styleable as -fx-show-header.'), Property('title', 'StringProperty', 'Untitled', 'Header title.'), Property('subtitle', 'StringProperty', 'empty string', 'Header subtitle.'), Property('titlePostfix', 'StringProperty', 'empty string', 'Small text after the title.'), Property('titleGraphic / titlePostfixGraphic / subtitleGraphic', 'ObjectProperty&lt;Node&gt;', 'null', 'Optional graphics in the header.'), Property('extras', 'ObjectProperty&lt;Node&gt;', 'null', 'Optional node at the end of the header.')], caption=None)]),
        Chapter('Predicate model', [Para('Every selected filter is a Predicate. Filters inside one FilterGroup are alternatives and therefore ORed together. The result of each group is ANDed with the other groups, the optional text predicate, and the additionalFilterPredicate.'), Figure(f"{G}/predicate.svg", 'How FilterView combines predicates.'), Callout('If a group has no selected filters, that group does not restrict the result set.', kind='note')]),
        Chapter('Chips and selected filters', [Para("The skin displays selected filters as chips. The filter text also becomes a chip using the bundle pattern <font face='Courier'>format.filter-text-quoted</font>."), Figure(f"{G}/chips.svg", 'Selected filters and search text become chips.'), Figure(f"{G}/scrolling.svg", 'Large chip sets use a ScrollPane after scrollThreshold is exceeded.')]),
        Chapter('FilterGroup and Filter classes', [PropertyTable([Property('FilterGroup.name', 'StringProperty', 'Untitled', 'Name shown on the group menu button.'), Property('FilterGroup.id', 'StringProperty', 'derived from name', 'Identifier derived from the name by replacing separators.'), Property('FilterGroup.filters', 'ObservableList&lt;Filter&lt;T&gt;&gt;', 'empty list', 'Filters displayed in the group menu.'), Property('Filter.name', 'StringProperty', 'Untitled', 'Name shown in the menu and chip.'), Property('Filter.id', 'StringProperty', 'derived from name', 'Identifier for the filter.'), Property('Filter.selected', 'BooleanProperty', 'constructor value', 'Whether the predicate participates in filtering.'), Property('Filter.group', 'ObjectProperty&lt;FilterGroup&lt;T&gt;&gt;', 'set by group', 'Back reference to the owning group.')], caption=None)]),
        Chapter('Styling', [Table(['Style class', 'Description'], [['.filter-view', 'Root control style class.'], ['.filter-container', 'Main container in the skin.'], ['.header-box', 'Title, subtitle, search field and extras.'], ['.title-subtitle-box, .title-box, .title, .title-postfix, .subtitle', 'Header text containers and labels.'], ['.filter-groups', 'Container for group menu buttons.'], ['.filters', 'Container for selected filter chips.'], ['.clear-filter-label', 'Action label that clears text and selected filters.']]), Table(['CSS property', 'Type', 'Default'], [['-fx-show-header', 'boolean', 'true']]), Code('.filter-view {\n    -fx-show-header: true;\n}\n.filter-view .clear-filter-label {\n    -fx-underline: true;\n}', caption='Example CSS for FilterView.')]),
        Chapter('Localization', [Table(['Key', 'English default'], [['title.untitled', 'Untitled'], ['group.name.untitled', 'Untitled'], ['filter.name.untitled', 'Untitled'], ['menu.select-all', 'All'], ['menu.select-none', 'None'], ['action.clear-filter', 'Clear Filter'], ['format.filter-text-quoted', '"{0}"'], ['accessible.role-description', 'filter']])]),
        Chapter('Accessibility', [Para("FilterView sets <font face='Courier'>AccessibleRole.NODE</font> and uses AccessibilityUtil with the localized role description <i>filter</i>.")]),
        Chapter('Recipes', [Section('Bind to a TableView'), Code('SortedList<Person> sorted = new SortedList<>(filterView.getFilteredItems());\nsorted.comparatorProperty().bind(table.comparatorProperty());\ntable.setItems(sorted);', caption=None), Section('Add an always-on predicate'), Code('filterView.setAdditionalFilterPredicate(person -> person.isActive());', caption=None), Section('Hide the header'), Code('filterView.setShowHeader(false);', caption=None), Section('Clear search and selections'), Code('filterView.getFilters().forEach(f -> f.setSelected(false));\nfilterView.setFilterText("");', caption=None), Section('Checklist'), Numbered(['Group alternatives that should OR together.', 'Put independent dimensions into separate groups.', 'Keep textFilterProvider null unless a search field is useful.', 'Use FilterView when you need data filtering; use SimpleFilterView for lightweight input chips.'])]),
        Chapter('See also', [Bullets(["Demo app: <font face='Courier'>FilterViewApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.FilterViewApp</font>.", 'Related controls: SimpleFilterView, ChipsViewContainer and SearchTextField.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
