from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table

G = "info-center-pane"

MANUAL = Manual(
    control="InfoCenterPane",
    package="com.dlsc.gemsfx.infocenter",
    subtitle="An overlay notification center with grouping, stacking and auto-hide",
    abstract='InfoCenterPane is a StackPane that overlays an InfoCenterView on top of application content. The view manages notification groups, stacked notifications, show-all lists, actions, pinning and click behaviours.',
    cover_svg=f"{G}/cover.svg",
    cover_caption="Notifications slide over application content and can be grouped, stacked, pinned and dismissed.",
    chapters=[
        Chapter('Introduction', [Para("<b>InfoCenterPane</b> extends <font face='Courier'>StackPane</font>. It owns one <font face='Courier'>InfoCenterView</font> and shows that view as a sliding overlay above the application content."), Section('Key features'), Bullets(['Notification groups with pinned and unpinned sections.', 'Stacked collapsed notifications and expanded group views.', 'Show-all mode for groups with many notifications.', 'Notification actions and OnClickBehaviour results.', 'Automatic showing when notifications are added.', 'Pinned and auto-hide modes.', 'Six overlay positions through InfoCenterViewPos.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="The class is in <font face='Courier'>com.dlsc.gemsfx.infocenter</font>.")]),
        Chapter('Getting started', [Code('InfoCenterPane pane = new InfoCenterPane();\npane.setContent(applicationRoot);\n\nNotificationGroup<Object, Notification<Object>> group = new NotificationGroup<>("Mail");\npane.getInfoCenterView().getGroups().add(group);\n\nNotification<Object> notification = new Notification<>("New mail", "Quarterly report arrived");\nnotification.getActions().add(new NotificationAction<>("Open", n -> Notification.OnClickBehaviour.HIDE_AND_REMOVE));\ngroup.getNotifications().add(notification);', caption='A pane with one group and one notification.'), Figure(f"{G}/cover.svg", 'InfoCenterPane overlays an InfoCenterView on application content.')]),
        Chapter('Anatomy', [Figure(f"{G}/anatomy.svg", 'The parts of InfoCenterPane and InfoCenterView.'), Table(['Part', 'Description'], [['Content', 'The application node set with contentProperty.'], ['InfoCenterView', 'The overlay view owned by the pane.'], ['NotificationGroup', 'Named list of notifications with sorting, pinning and expansion state.'], ['NotificationView', 'Visual representation of one notification.'], ['NotificationAction', 'Action button returning an OnClickBehaviour.']])]),
        Chapter('Pane API', [PropertyTable([Property('content', 'ObjectProperty&lt;Node&gt;', 'null', 'Application content filling the InfoCenterPane.'), Property('infoCenterView', 'read-only InfoCenterView', 'created in constructor', 'The overlay view containing notification groups.'), Property('showInfoCenter', 'BooleanProperty', 'false', 'Shows or hides the overlay.'), Property('infoCenterViewPos', 'ObjectProperty&lt;InfoCenterViewPos&gt;', 'TOP_RIGHT', 'Placement: top, center or bottom on the left or right side.'), Property('pinned', 'BooleanProperty', 'false', 'Pinned panes remain visible; changing to true shows the pane.'), Property('autoHide', 'BooleanProperty', 'true', 'When true, background/content clicks and the timer can hide an unpinned pane.'), Property('autoHideDuration', 'ObjectProperty&lt;Duration&gt;', '5 seconds', 'Time before an unpinned pane hides while the pointer is outside.'), Property('slideInDuration', 'ObjectProperty&lt;Duration&gt;', '200 ms', 'Duration for pane show/hide animation.'), Property('insideInfoCenter', 'ReadOnlyBooleanProperty', 'false', 'True while the mouse is inside the InfoCenterView.')], caption=None), Callout('The Java source recommends wrapping InfoCenterPane in another StackPane instead of using it directly as the Scene root on Windows, to avoid occasional platform-specific ghost images.', kind='warning')]),
        Chapter('InfoCenterView API', [PropertyTable([Property('groups', 'ObservableList&lt;NotificationGroup&lt;?, ?&gt;&gt;', 'empty list', 'Groups displayed in the center.'), Property('unmodifiableNotifications', 'ReadOnlyObservableList', 'flattened list', 'All notifications across groups.'), Property('pinnedGroups / unpinnedGroups', 'read-only lists', 'derived', 'Groups split by pinned state.'), Property('autoOpenGroup', 'BooleanProperty', 'false', 'Auto-expands groups. Styleable on InfoCenterView.'), Property('showAllGroup', 'ObjectProperty&lt;NotificationGroup&gt;', 'null', 'When set, switches to the single-group list view.'), Property('transparent', 'BooleanProperty', 'false', 'Adds style class transparent. Styleable.'), Property('placeholder', 'ObjectProperty&lt;Node&gt;', 'Label("No notifications")', 'Displayed when there are no notifications.'), Property('notificationSpacing', 'DoubleProperty', '10', 'Spacing between notification views. Styleable.'), Property('showAllFadeDuration / expandDuration / slideInDuration', 'ObjectProperty&lt;Duration&gt;', '300 ms / 300 ms / 500 ms', 'Animation timings styleable on InfoCenterView.'), Property('slideInOrigin', 'ObjectProperty&lt;Side&gt;', 'RIGHT', 'Slide side, bound by InfoCenterPane from its position. Styleable and reflected by :left/:right.')], caption=None), Para('The pane binds the view slide-in origin from the horizontal side of infoCenterViewPos, so left positions slide from the left and right positions slide from the right.')]),
        Chapter('Notification model', [PropertyTable([Property('Notification.title', 'StringProperty', 'constructor value', 'Required notification title.'), Property('Notification.summary', 'StringProperty', 'constructor value', 'Required summary text.'), Property('Notification.dateTime', 'ObjectProperty&lt;ZonedDateTime&gt;', 'now or constructor value', 'Timestamp used for sorting and relative labels.'), Property('Notification.type', 'ObjectProperty&lt;Type&gt;', 'INFO', 'INFO, WARNING, ERROR or SUCCESS; affects style classes. ERROR uses danger style. '), Property('Notification.onClick', 'ObjectProperty&lt;Callback&gt;', 'HIDE_AND_REMOVE', 'Returns NONE, REMOVE, HIDE or HIDE_AND_REMOVE.'), Property('Notification.actions', 'ObservableList&lt;NotificationAction&gt;', 'empty list', 'Buttons shown when a notification is expanded.'), Property('NotificationGroup.name', 'StringProperty', 'constructor value', 'Group heading.'), Property('NotificationGroup.sortOrder', 'IntegerProperty', '0', 'Comparable ordering before name fallback.'), Property('NotificationGroup.maximumNumberOfNotifications', 'IntegerProperty', '10', 'Collapsed group limit before show-all is offered.'), Property('NotificationGroup.expanded / pinned / pinnable', 'BooleanProperty', 'false / false / true', 'Expansion and pinning state.'), Property('NotificationGroup.viewFactory', 'ObjectProperty&lt;Callback&gt;', 'new NotificationView(notification)', 'Factory for custom notification views.')], caption=None), Figure(f"{G}/model.svg", 'Model objects used by the info center.')]),
        Chapter('Grouping, stacking and show all', [Para('A collapsed group can render notifications as a stack. Clicking a collapsed group expands it; groups with more items than maximumNumberOfNotifications expose a show-all mode backed by a single ListView.'), Figure(f"{G}/stacking.svg", 'Collapsed stack and expanded group presentation.'), Bullets(['Adding a notification sets its group and binds notification.expanded bidirectionally to group.expanded.', 'autoCollapse collapses groups when the notification count drops below two.', 'clearAll() removes all notifications from all groups.'])]),
        Chapter('Pinning and auto-hide', [Para('The pane shows itself when an InfoCenterEvent.NOTIFICATION_ADDED event is fired. It hides on HIDE events, background/content clicks or the auto-hide timer when autoHide is true and the pane is not pinned.'), Figure(f"{G}/positions.svg", 'InfoCenterViewPos controls placement and slide origin.'), Bullets(['pinned=true immediately shows the pane.', 'When unpinned notifications become empty and the pane is not pinned, it hides.', 'Mouse enter and exit maintain insideInfoCenter for the auto-hide timer.'])]),
        Chapter('Actions and click behaviour', [Para("Notification clicks and action buttons return an <font face='Courier'>OnClickBehaviour</font>. NONE leaves everything unchanged, REMOVE removes the notification, HIDE hides the pane, and HIDE_AND_REMOVE does both."), Code('notification.setOnClick(n -> Notification.OnClickBehaviour.REMOVE);\nnotification.getActions().add(new NotificationAction<>("Archive", n -> {\n    archive(n.getUserObject());\n    return Notification.OnClickBehaviour.HIDE_AND_REMOVE;\n}));', caption='Custom click and action behaviour.')]),
        Chapter('Styling', [Table(['Style class / pseudo class', 'Description'], [['.info-center-pane', 'Root StackPane of the pane.'], ['.info-center-view', 'Overlay view root.'], ['.main-pane, .top-level-container', 'Main containers in the view skin.'], ['.groups-container, .group-view, .header', 'Group containers and headers.'], ['.show-all-button, .show-less-button, .pin-button, .clear-button', 'Group action buttons.'], ['.single-group-list-view', 'ListView used by showAllGroup mode.'], ['.notification-view', 'Notification view root.'], ['.info, .warning, .danger, .success', 'Notification type classes.'], ['.stack-notification1, .stack-notification2, .small-stack, .big-stack', 'Stacking decoration classes.'], ['.transparent', 'Transparent InfoCenterView variant.'], [':expanded, :left, :right', 'Pseudo classes for expanded notification and slide origin.']]), Table(['InfoCenterView CSS property', 'Default'], [['-fx-auto-open-group', 'false'], ['-fx-show-all-fade-duration', '300ms'], ['-fx-expand-duration', '300ms'], ['-fx-slide-in-duration', '500ms'], ['-fx-slide-in-origin', 'RIGHT'], ['-fx-transparent', 'false'], ['-fx-notification-spacing', '10']]), Code('.info-center-view {\n    -fx-notification-spacing: 12px;\n    -fx-slide-in-origin: RIGHT;\n}\n.notification-view.warning {\n    -fx-font-weight: bold;\n}', caption='Example CSS for InfoCenterView.')]),
        Chapter('Localization', [Table(['Bundle / key', 'English default'], [['info-center-view: show-all', 'Show All'], ['info-center-view: show-less', 'Show Less'], ['info-center-view: close-group', 'Close Group'], ['info-center-view: clear-all', 'Remove all notifications'], ['info-center-view: placeholder', 'No notifications'], ['info-center-view: accessible.role-description', 'notifications'], ['notification-view: clear-all', 'Clear All'], ['notification-view: time.now', 'now'], ['notification-view: time.hours-ago', 'h ago'], ['notification-view: time.minutes-ago', 'm ago'], ['notification-view: time.yesterday', 'Yesterday'], ['notification-view: time.days-ago', 'days ago']])]),
        Chapter('Accessibility', [Para("InfoCenterView sets <font face='Courier'>AccessibleRole.LIST_VIEW</font> and uses the localized role description <i>notifications</i>. InfoCenterPane itself is a StackPane wrapper around that accessible view.")]),
        Chapter('Recipes', [Section('Pin the center'), Code('infoCenterPane.setPinned(true);', caption=None), Section('Change the overlay position'), Code('infoCenterPane.setInfoCenterViewPos(InfoCenterViewPos.BOTTOM_LEFT);', caption=None), Section('Use a custom view'), Code('group.setViewFactory(notification -> {\n    NotificationView<Object, MyNotification> view = new NotificationView<>(notification);\n    view.setContent(createDetails(notification));\n    return view;\n});', caption=None), Section('Clear all notifications'), Code('infoCenterPane.getInfoCenterView().clearAll();', caption=None), Section('Checklist'), Numbered(['Create groups first and add them to InfoCenterView.', 'Use sortOrder for stable group ordering.', 'Choose OnClickBehaviour deliberately for each notification type.', 'Keep pinned groups short by adjusting maximumNumberOfNotifications.'])]),
        Chapter('See also', [Bullets(["Demo app: <font face='Courier'>InfoCenterApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.InfoCenterApp</font>.", 'Related classes: InfoCenterView, NotificationGroup, Notification, NotificationView and NotificationAction.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
