# Content of the LoadingPane developer manual.
from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, PageBreak, Para, Property, PropertyTable, Section, Table
G='loading-pane'
MANUAL=Manual(control='LoadingPane',package='com.dlsc.gemsfx',subtitle='A StackPane wrapper for loading and error feedback',abstract=('LoadingPane wraps a content node and switches between normal content, progress feedback and an error node. It delays committing LOADING to avoid flicker, binds its progress to the active progress indicator and exposes CSS hooks for indicator size.'),cover_svg=f'{G}/cover.svg',cover_caption='LoadingPane replaces wrapped content with progress feedback or an error message.',chapters=[
Chapter('Introduction',[Para('<b>LoadingPane</b> extends <font face="Courier">StackPane</font> and is annotated with <font face="Courier">@DefaultProperty("content")</font>. It is useful around tables, lists, forms or dashboards that need to show loading and failure states without rebuilding the surrounding scene graph.'),Bullets(['Status <font face="Courier">OK</font> shows the content node.','Status <font face="Courier">LOADING</font> shows a progress indicator wrapper.','Status <font face="Courier">ERROR</font> shows an error node.','Progress value <font face="Courier">1.0</font> automatically returns the pane to <font face="Courier">OK</font>.','Convenience methods <font face="Courier">load()</font>, <font face="Courier">ok()</font> and <font face="Courier">error(...)</font> are thread-safe via <font face="Courier">Platform.runLater</font>.']),Code('''Label content = new Label("Some content goes here...");
LoadingPane pane = new LoadingPane(content);
pane.load();''')]),
Chapter('Getting started',[Para('Create the pane with a content node or set <font face="Courier">content</font> later. The default progress indicator is a <font face="Courier">CircleProgressIndicator</font> with an extra <font face="Courier">busy-indicator</font> style class.'),Code('''LoadingPane pane = new LoadingPane(tableView);
pane.setCommitDelay(200);

service.setOnRunning(evt -> pane.load());
service.setOnSucceeded(evt -> pane.ok());
service.setOnFailed(evt -> pane.error(service.getException()));
pane.progressProperty().bind(service.progressProperty());'''),Figure(f'{G}/states.svg','The committed status decides which child is visible and managed.'),Callout('Only the transition to LOADING is delayed. OK and ERROR commit without the loading delay.',kind='note')]),
Chapter('Anatomy',[Figure(f'{G}/anatomy.svg','The child layers maintained by LoadingPane.'),Table(['Part','Style class','Description'],[['Root','<font face="Courier">loading-pane</font>','The StackPane itself.'],['Content','application node','Visible only when committedStatus is OK.'],['Indicator wrapper','<font face="Courier">progress-indicator-wrapper</font>','StackPane around the progress indicator; its size is styled by pseudo-class.'],['Progress indicator','<font face="Courier">busy-indicator</font>','Default is CircleProgressIndicator; replaceable.'],['Error pane','<font face="Courier">error-pane</font>','Wrapper around errorNode.'],['Error label','<font face="Courier">error-label</font>','Default label with an icon and text bound to error.']],widths=[24,30,46])]),
Chapter('Control API',[PropertyTable([Property('content','ObjectProperty&lt;Node&gt;','null','Wrapped application content. Its visible property is bound to committedStatus == OK.'),Property('status','ObjectProperty&lt;Status&gt;','OK','Requested state: OK, LOADING or ERROR.'),Property('committedStatus','ReadOnlyObjectProperty&lt;Status&gt;','OK','Actual state after applying commitDelay for LOADING.'),Property('progress','DoubleProperty','0','Progress value bound to the active progress indicator. Setting 1.0 changes status to OK.'),Property('commitDelay','LongProperty','200','Delay in milliseconds before committing LOADING. Negative values throw IllegalArgumentException.'),Property('error','StringProperty','null','Text shown by the default error label.'),Property('errorNode','ObjectProperty&lt;Node&gt;','default Label','Node shown for ERROR.'),Property('progressIndicator','ObjectProperty&lt;ProgressIndicator&gt;','CircleProgressIndicator','Indicator used in LOADING and bound to progress.'),Property('size','ObjectProperty&lt;Size&gt;','MEDIUM','Styleable enum SMALL, MEDIUM or LARGE; reflected as pseudo-classes.')])]),
Chapter('Behaviour and state flow',[Figure(f'{G}/delay.svg','The delayed commit avoids short-lived loading flicker.'),Table(['Action','Effect'],[['<font face="Courier">load()</font>','Requests LOADING and clears error text.'],['<font face="Courier">ok()</font>','Requests OK and clears error text.'],['<font face="Courier">error(String)</font>','Requests ERROR and stores the message.'],['<font face="Courier">error(Throwable)</font>','Uses throwable message.'],['<font face="Courier">setProgress(1.0)</font>','Sets status to OK.']],widths=[38,62])]),
Chapter('Layout and sizing',[Figure(f'{G}/sizing.svg','The Size enum maps to wrapper dimensions in CSS.'),Para('The control rebuilds its child list when content, errorNode or progressIndicator changes. The progress indicator is placed inside an unmanaged-size wrapper whose preferred size comes from CSS. The indicator pref width and height are bound to the wrapper content area after padding.'),Table(['Size','Wrapper size from CSS'],[['SMALL','60px'],['MEDIUM','90px'],['LARGE','150px']],widths=[35,65]),PageBreak()]),
Chapter('Styling with CSS',[Para('The user agent stylesheet is <font face="Courier">loading-pane.css</font>.'),Table(['Selector','Purpose'],[['<font face="Courier">.loading-pane</font>','Root StackPane.'],['<font face="Courier">.progress-indicator-wrapper</font>','Wrapper around the current ProgressIndicator; default padding 20px and size 90px.'],['<font face="Courier">:small</font>','Wrapper size 60px.'],['<font face="Courier">:large</font>','Wrapper size 150px.'],['<font face="Courier">.error-pane &gt; .error-label</font>','Red centered wrapping error text.'],['<font face="Courier">.error-label .icon</font>','Built-in red error icon shape.']],widths=[48,52]),Table(['CSS property','Type','Default'],[['<font face="Courier">-fx-size</font>','Size enum','MEDIUM']],widths=[48,26,26]),Code('''.loading-pane {
    -fx-size: large;
}

.loading-pane > .error-pane > .error-label {
    -fx-text-fill: -fx-accent;
}'''),PageBreak()]),
Chapter('Recipes',[Section('Use a different indicator'),Code('''RingProgressIndicator ring = new RingProgressIndicator();
pane.setProgressIndicator(ring);
pane.progressProperty().bind(service.progressProperty());'''),Section('Replace the error node'),Code('''Label error = new Label();
error.textProperty().bind(pane.errorProperty());
error.getStyleClass().add("my-error");
pane.setErrorNode(error);'''),Section('Checklist'),Numbered(['Keep content visibility under LoadingPane control; it binds the visible property.','Use commitDelay to suppress flicker for fast operations.','Set progress to values below zero for indeterminate work.','Call ok() or error(...) from background callbacks; the methods marshal to the FX thread.']),PageBreak()]),
Chapter('Troubleshooting',[Bullets(['A negative commitDelay throws an IllegalArgumentException.','If the spinner is too large or small, set <font face="Courier">size</font> or style <font face="Courier">-fx-size</font>.','If replacing the progress indicator, use a ProgressIndicator subclass so progress binding exists.','The class does not set a custom AccessibleRole in the source.'])])])
