from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table

G = "paging-controls"

MANUAL = Manual(
    control="PagingControls",
    package="com.dlsc.gemsfx.paging",
    subtitle="Standalone pagination buttons and page-size controls",
    abstract='PagingControls is the standalone pagination control used by the paged list and grid controls. It renders range messages, numeric page indicators, first/previous/next/last navigation and an optional page-size selector. This manual documents its page model, keyboard behaviour, styling and localization hooks.',
    cover_svg=f"{G}/cover.svg",
    cover_caption="The control summarizes the current page and lets the user move through a larger result set.",
    chapters=[
        Chapter('Introduction', [Para("<b>PagingControls</b> is a JavaFX <font face='Courier'>Control</font> for navigating a zero-based paged data set. It does not load data itself; applications or higher-level controls update <font face='Courier'>totalItemCount</font>, <font face='Courier'>pageSize</font> and <font face='Courier'>page</font>."), Section('Key features'), Bullets(['Zero-based page model with derived pageCount.', 'Numeric page buttons with configurable maximum count.', 'First, previous, next and last navigation.', 'Optional page-size selector with configurable choices.', 'Range message label and localized button text.', 'Keyboard navigation using arrow, page, home and end keys.', 'Read-only needed property used by skins to hide unneeded controls.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="The class is in <font face='Courier'>com.dlsc.gemsfx.paging</font>.")]),
        Chapter('Getting started', [Para('Use PagingControls when the data view is built separately from the navigation bar.'), Code('PagingControls controls = new PagingControls();\ncontrols.setTotalItemCount(87);\ncontrols.setPageSize(10);\n\ncontrols.pageProperty().addListener((obs, oldPage, page) -> {\n    int offset = page.intValue() * controls.getPageSize();\n    loadRows(offset, controls.getPageSize());\n});', caption='A minimal standalone pager.'), Figure(f"{G}/cover.svg", 'PagingControls with a message, navigation buttons and a page-size selector.')]),
        Chapter('Anatomy', [Para('The skin arranges message, buttons and page-size controls in one pane. LEFT and RIGHT alignment use a horizontal layout; CENTER uses a vertical layout.'), Figure(f"{G}/anatomy.svg", 'The parts of the PagingControls skin.'), Table(['Part', 'Style class', 'Description'], [['.paging-controls', 'Root style class on PagingControls.'], ['.pane', 'Container used by the skin. It also receives horizontal or vertical.'], ['.message-label', 'Message label generated from the current range and total count.'], ['.buttons-container / .grid-pane', 'Container for navigation and page buttons.'], ['.page-button, .current', 'Numeric page buttons; current marks the selected page.'], ['.navigation-button', 'Base class for first, previous, next and last buttons.'], ['.page-size-container', 'Container for the page-size label and choice box.']])]),
        Chapter('Control API', [Section('Paging model'), PropertyTable([Property('page', 'IntegerProperty', '0', 'Zero-based current page. The base class clamps the value when the page count shrinks.'), Property('pageSize', 'IntegerProperty', '10', 'Number of items represented by one page.'), Property('totalItemCount', 'IntegerProperty', '0', 'Total number of items in the backing data set. It drives the derived page count.'), Property('pageCount', 'ReadOnlyIntegerProperty', '0', 'Computed from totalItemCount and pageSize, rounded up.')], caption=None), Section('Button and selector options'), PropertyTable([Property('availablePageSizes', 'ObservableList&lt;Integer&gt;', '5, 10, 15, 20, 30, 40, 50', 'Values shown by the page-size selector.'), Property('pageSizeSelectorLabel', 'StringProperty', 'Results per page', 'Label in front of the page-size choice box.'), Property('showPageSizeSelector', 'BooleanProperty', 'true', 'Shows the choice box when true. Styleable as -fx-show-page-size-selector.'), Property('sameWidthPageButtons', 'BooleanProperty', 'false', 'Gives all numeric page buttons the same width. Styleable as -fx-same-width-page-buttons.'), Property('showPreviousNextPageButton', 'BooleanProperty', 'true', 'Shows previous and next navigation buttons. Styleable as -fx-show-previous-next-page-button.'), Property('messageLabelStrategy', 'ObjectProperty&lt;MessageLabelStrategy&gt;', 'ALWAYS_SHOW', 'Controls whether the message label is visible. Styleable as -fx-message-label-strategy.'), Property('firstLastPageDisplayMode', 'ObjectProperty&lt;FirstLastPageDisplayMode&gt;', 'SHOW_PAGE_BUTTONS', 'Controls first/last page buttons or arrow buttons. Styleable as -fx-first-last-page-display-mode.'), Property('maxPageIndicatorsCount', 'IntegerProperty', '5', 'Maximum number of numeric page indicators. Styleable as -fx-max-page-indicators-count.')], caption=None), Section('Layout and visibility'), PropertyTable([Property('alignment', 'ObjectProperty&lt;HPos&gt;', 'HPos.RIGHT', 'Horizontal placement of the controls. Styleable as -fx-page-alignment.'), Property('needed', 'ReadOnlyBooleanProperty', 'false', 'True when the skin decides that visible controls are useful for the current page count and options.')], caption=None)]),
        Chapter('Page math and clamping', [Para("The control computes <font face='Courier'>pageCount</font> from <font face='Courier'>totalItemCount</font> and <font face='Courier'>pageSize</font>. When the total count or page size changes and the current page would be out of range, the current page is clamped."), Figure(f"{G}/page-math.svg", 'How item count and page size determine the number of pages.'), Callout('The current page is zero-based. Displayed page buttons are one-based for users.', kind='note')]),
        Chapter('Navigation behaviour', [Para('The skin disables navigation buttons that cannot move further. Keyboard handling maps RIGHT and PAGE_DOWN to the next page, LEFT and PAGE_UP to the previous page, HOME to the first page and END to the last page.'), Figure(f"{G}/keyboard.svg", 'Keyboard shortcuts exposed by PagingControls.'), Figure(f"{G}/modes.svg", 'First and last pages can be displayed as page buttons, arrow buttons or hidden by display mode.')]),
        Chapter('Styling', [Para("The user-agent stylesheet is <font face='Courier'>paging-controls.css</font>."), Table(['CSS property', 'Type', 'Default'], [['-fx-show-page-size-selector', 'boolean', 'true'], ['-fx-same-width-page-buttons', 'boolean', 'false'], ['-fx-show-previous-next-page-button', 'boolean', 'true'], ['-fx-message-label-strategy', 'enum', 'ALWAYS_SHOW'], ['-fx-first-last-page-display-mode', 'enum', 'SHOW_PAGE_BUTTONS'], ['-fx-max-page-indicators-count', 'integer', '5'], ['-fx-page-alignment', 'HPos', 'RIGHT']]), Code('.paging-controls {\n    -fx-page-alignment: CENTER;\n    -fx-max-page-indicators-count: 7;\n}\n.paging-controls .page-button.current {\n    -fx-font-weight: bold;\n}', caption='Example CSS for a centered pager.')]),
        Chapter('Localization', [Para('PagingControls resolves its text through ResourceBundleManager.'), Table(['Key', 'English default'], [['button.first', 'First'], ['button.last', 'Last'], ['button.previous', 'Previous'], ['button.next', 'Next'], ['message.items', 'showing range / total message'], ['label.page-size', 'Results per page']])]),
        Chapter('Accessibility', [Para("The constructor sets <font face='Courier'>AccessibleRole.PAGINATION</font>. The page buttons are regular JavaFX buttons, so assistive technologies can navigate the same actions as mouse and keyboard users.")]),
        Chapter('Recipes', [Section('Hide the page-size selector'), Code('controls.setShowPageSizeSelector(false);', caption=None), Section('Use a wider indicator window'), Code('controls.setMaxPageIndicatorsCount(9);', caption=None), Section('Center the bar'), Code('controls.setAlignment(HPos.CENTER);', caption=None), Section('Drive a table'), Code('controls.pageProperty().addListener((obs, old, page) -> reloadPage(page.intValue()));', caption=None), Section('Checklist'), Numbered(['Keep page zero-based in code and one-based in labels.', 'Update totalItemCount whenever the data source changes.', 'Choose availablePageSizes that your loader supports.', 'Localize button and message text when shipping translated applications.'])]),
        Chapter('See also', [Bullets(["Demo app: <font face='Courier'>PagingControlsApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.PagingControlsApp</font>.", 'Related controls: PagingListView and PagingGridTableView.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
