from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table

G = "paging-grid-table-view"

MANUAL = Manual(
    control="PagingGridTableView",
    package="com.dlsc.gemsfx.paging",
    subtitle="A paged GridTableView backed by an asynchronous loader",
    abstract='PagingGridTableView applies the shared item-paging loader contract to a GridTableView. It exposes a columns list, current page items, loading status, paging controls and open-item hooks for table-like page navigation.',
    cover_svg=f"{G}/cover.svg",
    cover_caption="A GridTableView receives one loaded page and a synchronized PagingControls bar.",
    chapters=[
        Chapter('Introduction', [Para("<b>PagingGridTableView</b> is the table counterpart of PagingListView. It embeds a <font face='Courier'>GridTableView</font>, binds its rows to <font face='Courier'>itemsOnCurrentPage</font>, and forwards columns, loading status, placeholder and open-item callbacks to the inner grid table."), Section('Key features'), Bullets(['Shared asynchronous paging loader.', 'Observable columns list bound into the inner GridTableView.', 'Optional filling of the last page by binding the minimum row count to pageSize.', 'Embedded PagingControls at top or bottom.', 'reload() for data loads and refresh() for row refreshes.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="The class is in <font face='Courier'>com.dlsc.gemsfx.paging</font>.")]),
        Chapter('Getting started', [Code('PagingGridTableView<Person> table = new PagingGridTableView<>();\ntable.getColumns().setAll(firstNameColumn, lastNameColumn);\n\ntable.setLoader(request -> {\n    int offset = request.getPage() * request.getPageSize();\n    return new PagingLoadResponse<>(repository.find(offset, request.getPageSize()),\n                                    repository.count());\n});', caption='A minimal paged grid table.'), Figure(f"{G}/cover.svg", 'PagingGridTableView shows a grid table and a paging bar.')]),
        Chapter('Anatomy', [Figure(f"{G}/anatomy.svg", 'The parts of PagingGridTableView.'), Table(['Part', 'Style class', 'Description'], [['.paging-grid-table-view', 'Root style class.'], ['.content', 'Container for grid table and paging controls.'], ['GridTableView classes', 'The inner grid table keeps its own table-specific style classes.']])]),
        Chapter('Control API', [Section('Shared item paging properties'), PropertyTable([Property('loader', 'ObjectProperty&lt;Callback&lt;PagingLoadRequest, PagingLoadResponse&lt;T&gt;&gt;&gt;', 'LoadingService default callback', 'Callback that receives zero-based page and pageSize and returns items plus the total count.'), Property('itemsOnCurrentPage', 'ReadOnlyListProperty&lt;T&gt;', 'empty list', 'Items returned by the latest successful load and shown by the inner view.'), Property('loadingStatus', 'ReadOnlyObjectProperty&lt;LoadingStatus&gt;', 'OK', 'OK, LOADING or ERROR based on the internal LoadingService state.'), Property('loadDelayInMillis', 'LongProperty', '50', 'Delay before the control starts a load. Negative values are rejected.'), Property('commitLoadStatusDelay', 'LongProperty', '400', 'Delay before the loading status is committed to the UI.'), Property('fillLastPage', 'BooleanProperty', 'false', 'Pads the last page layout where supported. Styleable as -fx-fill-last-page.'), Property('pagingControlsLocation', 'ObjectProperty&lt;Side&gt;', 'Side.BOTTOM', 'Places controls at TOP or BOTTOM. LEFT and RIGHT are not supported and reset to BOTTOM.'), Property('showPagingControls', 'BooleanProperty', 'true', 'Shows or hides embedded PagingControls. Styleable as -fx-show-paging-controls.'), Property('usingScrollPane', 'BooleanProperty', 'false', 'Wraps the content in a ScrollPane when true. Styleable as -fx-use-scroll-pane.'), Property('placeholder', 'ObjectProperty&lt;Node&gt;', 'Label("No items")', 'Node shown when the current page has no content.'), Property('onOpenItem', 'ObjectProperty&lt;Consumer&lt;T&gt;&gt;', 'null', 'Callback invoked by the inner item view when an item is opened.'), Property('selectionModel', 'ObjectProperty&lt;MultipleSelectionModel&lt;T&gt;&gt;', 'control-specific model', 'Selection model of the inner list or grid table.')], caption=None), Section('Grid-table properties'), PropertyTable([Property('columns', 'ObservableList&lt;GridTableColumn&lt;T, ?&gt;&gt;', 'empty list', 'Columns bound into the internal GridTableView.'), Property('selectionModel', 'ObjectProperty&lt;MultipleSelectionModel&lt;T&gt;&gt;', 'inner GridTableView model', 'Selection model used by the inner grid table.')], caption=None)]),
        Chapter('Loader contract', [Para('The data-loading contract is identical to PagingListView. A request contains page and pageSize; a response returns the page items and the total count. The service updates loadingStatus and itemsOnCurrentPage after a successful callback.'), Figure(f"{G}/loading.svg", 'Request and response flow for a grid table page.'), Callout("The loader callback should not return null items. Use <font face='Courier'>PagingLoadResponse.emptyResponse()</font> for empty results.", kind='note')]),
        Chapter('Columns and rows', [Para("The control exposes the inner table columns through <font face='Courier'>getColumns()</font>. Set them once, then update the loader independently."), Figure(f"{G}/columns.svg", 'Columns are bound into the internal GridTableView.'), Figure(f"{G}/last-page.svg", 'fillLastPage controls whether the last page keeps the same row footprint.')]),
        Chapter('Refresh and opening items', [Para("<font face='Courier'>refresh()</font> delegates to the inner GridTableView refresh. <font face='Courier'>reload()</font> restarts the LoadingService. <font face='Courier'>onOpenItem</font> is forwarded to the grid table for item activation.")]),
        Chapter('Styling', [Table(['Style class', 'Description'], [['.paging-grid-table-view', 'Root style class.'], ['.content', 'Container for grid table and paging controls.'], ['GridTableView classes', 'The inner grid table keeps its own table-specific style classes.']]), Table(['CSS property', 'Type', 'Default'], [['-fx-fill-last-page', 'boolean', 'false'], ['-fx-paging-controls-location', 'Side', 'BOTTOM'], ['-fx-show-paging-controls', 'boolean', 'true'], ['-fx-use-scroll-pane', 'boolean', 'false'], ['-fx-show-page-size-selector', 'boolean', 'true'], ['-fx-same-width-page-buttons', 'boolean', 'false'], ['-fx-show-previous-next-page-button', 'boolean', 'true'], ['-fx-message-label-strategy', 'enum', 'ALWAYS_SHOW'], ['-fx-first-last-page-display-mode', 'enum', 'SHOW_PAGE_BUTTONS'], ['-fx-max-page-indicators-count', 'integer', '5'], ['-fx-page-alignment', 'HPos', 'RIGHT']]), Code('.paging-grid-table-view {\n    -fx-fill-last-page: true;\n    -fx-paging-controls-location: BOTTOM;\n}\n.paging-grid-table-view > .stack-pane > .content {\n    -fx-spacing: 8px;\n}', caption='Example CSS for PagingGridTableView.')]),
        Chapter('Localization', [Para('The embedded PagingControls use the paging-control bundle. The item-paging placeholder uses the English default <i>No items</i>.')]),
        Chapter('Accessibility', [Para("PagingGridTableView sets <font face='Courier'>AccessibleRole.TABLE_VIEW</font>. The inner grid table provides row and column semantics while the embedded pager remains keyboard-operable.")]),
        Chapter('Recipes', [Section('Fill the last page'), Code('table.setFillLastPage(true);', caption=None), Section('Move controls to the top'), Code('table.setPagingControlsLocation(Side.TOP);', caption=None), Section('Open row details'), Code('table.setOnOpenItem(person -> detailsPane.setPerson(person));', caption=None), Section('Reload after filter changes'), Code('filter.textProperty().addListener(obs -> table.reload());', caption=None), Section('Checklist'), Numbered(['Return totalItemCount for the unpaged query.', 'Keep columns independent from the loader.', 'Use fillLastPage only when a stable table height is desired.', 'Use refresh() for visible row repainting, not for data queries.'])]),
        Chapter('See also', [Bullets(["Demo app: <font face='Courier'>PagingGridTableViewApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.PagingGridTableViewApp</font>.", 'Related controls: PagingControls, PagingListView and GridTableView.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
