from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table

G = "paging-list-view"

MANUAL = Manual(
    control="PagingListView",
    package="com.dlsc.gemsfx.paging",
    subtitle="A ListView backed by an asynchronous page loader",
    abstract='PagingListView combines a ListView, PagingControls and the ItemPagingControlBase loading contract. It requests one page at a time from a callback, displays the returned items and exposes loading, placeholder, selection and open-item hooks.',
    cover_svg=f"{G}/cover.svg",
    cover_caption="A ListView page and its controls are loaded through the shared paging callback contract.",
    chapters=[
        Chapter('Introduction', [Para("<b>PagingListView</b> is a paged list control. It owns an internal <font face='Courier'>ListView</font>, binds that list to the current page items, and uses an internal <font face='Courier'>LoadingService</font> to call the configured loader."), Section('Key features'), Bullets(['Asynchronous loader based on PagingLoadRequest and PagingLoadResponse.', 'Embedded PagingControls with top or bottom placement.', 'Multiple-selection model from the internal ListView.', 'Custom cell factory and progress indicator.', 'Placeholder for empty pages.', 'reload() restarts the service; refresh() refreshes visible cells.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="The class is in <font face='Courier'>com.dlsc.gemsfx.paging</font>.")]),
        Chapter('Getting started', [Code('PagingListView<Person> view = new PagingListView<>();\nview.setLoader(request -> {\n    int offset = request.getPage() * request.getPageSize();\n    List<Person> page = repository.find(offset, request.getPageSize());\n    return new PagingLoadResponse<>(page, repository.count());\n});\n\nview.setCellFactory(list -> new ListCell<>() {\n    @Override\n    protected void updateItem(Person item, boolean empty) {\n        super.updateItem(item, empty);\n        setText(empty || item == null ? null : item.getLastName());\n    }\n});', caption='A complete loader and cell factory.'), Figure(f"{G}/cover.svg", 'PagingListView wraps a ListView and a PagingControls bar.')]),
        Chapter('Anatomy', [Para('The skin places the internal ListView in a StackPane so it can overlay a placeholder or loading indicator. PagingControls are placed above or below that content.'), Figure(f"{G}/anatomy.svg", 'The parts of PagingListView.'), Table(['Part', 'Style class', 'Description'], [['.paging-list-view', 'Root style class.'], ['.inner-list-view', 'Internal ListView.'], ['.stack-pane', 'Stack containing content, placeholder and progress.'], ['.content', 'Container spacing for view and paging controls.'], ['.list-cell:selected', 'Selected cell styling from paging-list-view.css.']])]),
        Chapter('Control API', [Section('Shared item paging properties'), PropertyTable([Property('loader', 'ObjectProperty&lt;Callback&lt;PagingLoadRequest, PagingLoadResponse&lt;T&gt;&gt;&gt;', 'LoadingService default callback', 'Callback that receives zero-based page and pageSize and returns items plus the total count.'), Property('itemsOnCurrentPage', 'ReadOnlyListProperty&lt;T&gt;', 'empty list', 'Items returned by the latest successful load and shown by the inner view.'), Property('loadingStatus', 'ReadOnlyObjectProperty&lt;LoadingStatus&gt;', 'OK', 'OK, LOADING or ERROR based on the internal LoadingService state.'), Property('loadDelayInMillis', 'LongProperty', '50', 'Delay before the control starts a load. Negative values are rejected.'), Property('commitLoadStatusDelay', 'LongProperty', '400', 'Delay before the loading status is committed to the UI.'), Property('fillLastPage', 'BooleanProperty', 'false', 'Pads the last page layout where supported. Styleable as -fx-fill-last-page.'), Property('pagingControlsLocation', 'ObjectProperty&lt;Side&gt;', 'Side.BOTTOM', 'Places controls at TOP or BOTTOM. LEFT and RIGHT are not supported and reset to BOTTOM.'), Property('showPagingControls', 'BooleanProperty', 'true', 'Shows or hides embedded PagingControls. Styleable as -fx-show-paging-controls.'), Property('usingScrollPane', 'BooleanProperty', 'false', 'Wraps the content in a ScrollPane when true. Styleable as -fx-use-scroll-pane.'), Property('placeholder', 'ObjectProperty&lt;Node&gt;', 'Label("No items")', 'Node shown when the current page has no content.'), Property('onOpenItem', 'ObjectProperty&lt;Consumer&lt;T&gt;&gt;', 'null', 'Callback invoked by the inner item view when an item is opened.'), Property('selectionModel', 'ObjectProperty&lt;MultipleSelectionModel&lt;T&gt;&gt;', 'control-specific model', 'Selection model of the inner list or grid table.')], caption=None), Section('List-specific properties'), PropertyTable([Property('cellFactory', 'ObjectProperty&lt;Callback&lt;ListView&lt;T&gt;, ListCell&lt;T&gt;&gt;&gt;', 'default text cell', 'Factory used by the internal ListView.'), Property('progressIndicator', 'ObjectProperty&lt;Node&gt;', 'CircleProgressIndicator', 'Node shown while loading is committed.')], caption=None)]),
        Chapter('Loader contract', [Para("The loader receives a <font face='Courier'>PagingLoadRequest</font> with zero-based page and pageSize. It must return a non-null item list and the total item count for the whole data set. The control updates <font face='Courier'>itemsOnCurrentPage</font> and page count from the response."), Figure(f"{G}/loading.svg", 'Data flow from page change to ListView items.'), Callout("For in-memory lists, <font face='Courier'>SimpleLoader</font> slices the backing list with offset <font face='Courier'>page * pageSize</font> and reloads when that list changes.", kind='tip')]),
        Chapter('Loading, empty and error states', [Para('While the service is running, loadingStatus becomes LOADING. On success it becomes OK; on failure it becomes ERROR. The placeholder is visible when no items are available for the current page.'), Figure(f"{G}/states.svg", 'Normal, loading and placeholder states.'), Bullets(['loadDelayInMillis defaults to 50 ms on the control.', 'commitLoadStatusDelay defaults to 400 ms.', 'Negative load delays are rejected.', 'Cancelled service work is ignored.'])]),
        Chapter('Layout and refresh', [Para('Paging controls can appear above or below the list. LEFT and RIGHT locations are not supported by ItemPagingControlBase and are reset to BOTTOM.'), Figure(f"{G}/layout.svg", 'Top and bottom paging-control placement.'), Para("<font face='Courier'>reload()</font> starts a new load from the configured loader. <font face='Courier'>refresh()</font> only refreshes the visible ListView cells and does not query the data source.")]),
        Chapter('Styling', [Table(['Style class', 'Description'], [['.paging-list-view', 'Root style class.'], ['.inner-list-view', 'Internal ListView.'], ['.stack-pane', 'Stack containing content, placeholder and progress.'], ['.content', 'Container spacing for view and paging controls.'], ['.list-cell:selected', 'Selected cell styling from paging-list-view.css.']]), Table(['CSS property', 'Type', 'Default'], [['-fx-fill-last-page', 'boolean', 'false'], ['-fx-paging-controls-location', 'Side', 'BOTTOM'], ['-fx-show-paging-controls', 'boolean', 'true'], ['-fx-use-scroll-pane', 'boolean', 'false'], ['-fx-show-page-size-selector', 'boolean', 'true'], ['-fx-same-width-page-buttons', 'boolean', 'false'], ['-fx-show-previous-next-page-button', 'boolean', 'true'], ['-fx-message-label-strategy', 'enum', 'ALWAYS_SHOW'], ['-fx-first-last-page-display-mode', 'enum', 'SHOW_PAGE_BUTTONS'], ['-fx-max-page-indicators-count', 'integer', '5'], ['-fx-page-alignment', 'HPos', 'RIGHT']]), Code('.paging-list-view {\n    -fx-paging-controls-location: TOP;\n    -fx-show-paging-controls: true;\n}\n.paging-list-view .inner-list-view .list-cell:selected {\n    -fx-font-weight: bold;\n}', caption='Example CSS for PagingListView.')]),
        Chapter('Localization', [Para('The embedded PagingControls use the paging-control bundle. The default placeholder comes from the item-paging-control bundle and displays <i>No items</i>.')]),
        Chapter('Accessibility', [Para("PagingListView sets <font face='Courier'>AccessibleRole.LIST_VIEW</font>. The embedded list exposes normal ListView selection and focus behaviour.")]),
        Chapter('Recipes', [Section('Use an in-memory list'), Code('ObservableList<Person> all = FXCollections.observableArrayList();\nview.setLoader(new SimpleLoader<>(all));', caption=None), Section('Open selected item'), Code('view.setOnOpenItem(person -> showDetails(person));', caption=None), Section('Hide controls for a fixed first page'), Code('view.setShowPagingControls(false);', caption=None), Section('Refresh cells without loading'), Code('view.refresh();', caption=None), Section('Checklist'), Numbered(['Return the total count for the entire data set, not just the page.', 'Keep loader work off the JavaFX application thread.', 'Use reload() after changing query parameters.', 'Use refresh() only when existing cell visuals changed.'])]),
        Chapter('See also', [Bullets(["Demo app: <font face='Courier'>PagingListViewApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.PagingListViewApp</font>.", 'Related controls: PagingControls and PagingGridTableView.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
