from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, PageBreak, Para, Property, PropertyTable, Section, Table

G = "payment-option-view"

MANUAL = Manual(
    control="PaymentOptionView",
    package="com.dlsc.gemsfx",
    subtitle="An ImageView for bundled payment-brand artwork",
    abstract='PaymentOptionView is a small ImageView subclass that renders bundled payment option images. The option enum chooses a provider or card brand, the theme enum chooses dark or light artwork, and ImageView sizing preserves the resource aspect ratio.',
    cover_svg=f"{G}/cover.svg",
    cover_caption='PaymentOptionView displays payment option artwork with dark or light bundled PNG resources.',
    chapters=[
        Chapter('Introduction', [Para("<b>PaymentOptionView</b> extends <font face='Courier'>ImageView</font>. It does not use a skin or CSS file; changing the option or theme selects a bundled PNG resource from <font face='Courier'>paymentoptions/</font>."), Section('Key features'), Bullets(['55 option enum constants including card networks, wallets, bank transfer and providers.', 'Two resource themes: DARK and LIGHT.', 'Default option MASTERCARD and default theme DARK.', 'Default fitWidth 100 with preserveRatio true.', 'UNKNOWN clears the image.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="GemsFX controls live in module <font face='Courier'>com.dlsc.gemsfx</font>.")]),
        Chapter('Getting started', [Code('PaymentOptionView view = new PaymentOptionView();\n\nComboBox<PaymentOptionView.Option> optionsBox = new ComboBox<>();\noptionsBox.getItems().setAll(PaymentOptionView.Option.values());\noptionsBox.valueProperty().bindBidirectional(view.optionProperty());\n\nComboBox<PaymentOptionView.Theme> themeBox = new ComboBox<>();\nthemeBox.getItems().setAll(PaymentOptionView.Theme.values());\nthemeBox.valueProperty().bindBidirectional(view.themeProperty());\n\nview.setFitWidth(160);\nview.setPreserveRatio(true);', caption='The PaymentOptionApp demo binds option and theme combo boxes directly to the view.') , Figure(f"{G}/cover.svg", 'Payment option artwork in a checkout-style layout.')]),
        Chapter('Anatomy', [Figure(f"{G}/anatomy.svg", 'How option, theme and ImageView sizing work together.'), Table(['Part', 'Description'], [['ImageView', 'The control itself; no skin is created.'], ['option', 'Selects the base resource file name.'], ['theme', 'Appends -dark.png or -light.png.'], ['paymentoptions resources', 'Bundled PNG images, 500 by 300 in the source comment.'], ['fitWidth', 'Set to 100 by the constructor.'], ['preserveRatio', 'Set to true by the constructor.']])]),
        Chapter('Control API', [PropertyTable([Property('option','ObjectProperty&lt;Option&gt;','MASTERCARD','Payment option artwork to display. UNKNOWN clears the image.'), Property('theme','ObjectProperty&lt;Theme&gt;','DARK','DARK uses colored backgrounds; LIGHT uses white-background artwork.'), Property('fitWidth','DoubleProperty from ImageView','100','Constructor-set ImageView width.'), Property('preserveRatio','BooleanProperty from ImageView','true','Constructor-set ImageView ratio preservation.')])]),
        Chapter('Option enum', [Figure(f"{G}/options.svg", 'Representative payment options from the enum.'), Para("<font face='Courier'>UNKNOWN, CREDIT_CARD, CHECKOUT2, ALI_PAY, AMAZON, AMERICAN_EXPRESS, APPLE_PAY, BANCONTACT, BITCOIN, BITPAY, CIRRUS, CLICKANDBUY, COINKITE, DINERSCLUB, DIRECTDEBIT, DISCOVER, DWOLLA, EBAY, EWAY, GIROPAY, GOOGLEWALLET, INGENICO, JCB, KLARNA, LASER, MAESTRO, MASTERCARD, MONERO, NETELLER, OGONE, OKPAY, PAYBOX, PAYMILL, PAYONE, PAYONEER, PAYPAL, PAYSAFECARD, PAYU, PAYZA, RIPPLE, SAGE, SEPA, SHOPIFY, SKRILL, SOLO, SQUARE, STRIPE, SWITCH, UKASH, UNIONPAY, VERIFONE, VERISIGN, VISA, WEBMONEY, WESTERNUNION, WORLDPAY</font>")]),
        Chapter('Theme and resources', [Figure(f"{G}/themes.svg", 'The two themes map to -dark.png and -light.png resources.'), Bullets(['Resource file names are hard-coded in updateView().', 'Most options map directly to a provider name such as Visa, Paypal or MasterCard.', 'UNKNOWN leaves the file name blank and sets image to null.', 'Invalid enum handling in the switch throws an exception for unexpected values.'])]),
        Chapter('Sizing and layout', [Figure(f"{G}/sizing.svg", 'PaymentOptionView uses ImageView sizing; preserveRatio keeps card proportions.'), Para('Because the class extends ImageView, use standard ImageView sizing APIs such as fitWidth, fitHeight, preserveRatio and smooth. The constructor initializes only fitWidth and preserveRatio.'), Para('The demos keep the artwork at a consistent width and let layout containers do the rest: <font face=\'Courier\'>PaymentOptionApp</font> centers one view above option/theme selectors, while <font face=\'Courier\'>PaymentOptionTilesApp</font> places one view for every enum constant in a padded <font face=\'Courier\'>TilePane</font> with 10-pixel gaps.')]),
        Chapter('Styling', [Para("There is no <font face='Courier'>payment-option-view.css</font>, no style class added by the class, and no styleable CSS properties. Style layout containers around the ImageView or use ImageView effects directly.")]),
        Chapter('Localization and accessibility', [PageBreak(), Para('PaymentOptionView does not use ResourceBundleManager and does not set an AccessibleRole or accessible text in the verified source. Applications that need screen-reader text should set accessibleText themselves, for example to the selected brand name.')]),
        Chapter('Recipes', [PageBreak(), Section('Option selector'), Code('ComboBox<PaymentOptionView.Option> optionsBox = new ComboBox<>();\noptionsBox.getItems().setAll(PaymentOptionView.Option.values());\noptionsBox.valueProperty().bindBidirectional(view.optionProperty());', caption=None), Section('Theme selector with contrasting background'), Code('themeBox.valueProperty().bindBidirectional(view.themeProperty());\nthemeBox.valueProperty().addListener(it -> {\n    switch (themeBox.getValue()) {\n        case DARK -> parent.setStyle("-fx-background-color: white;");\n        case LIGHT -> parent.setStyle("-fx-background-color: rgb(57,73,92);");\n    }\n});', caption=None), Section('Tile all options'), Code('TilePane pane = new TilePane();\npane.setHgap(10);\npane.setVgap(10);\nfor (PaymentOptionView.Option option : PaymentOptionView.Option.values()) {\n    PaymentOptionView tile = new PaymentOptionView();\n    tile.setFitWidth(100);\n    tile.setPreserveRatio(true);\n    tile.themeProperty().bind(theme);\n    tile.setOption(option);\n    pane.getChildren().add(tile);\n}', caption=None), Section('Clear unsupported payment'), Code('view.setOption(PaymentOptionView.Option.UNKNOWN);', caption=None), Section('Checklist'), Numbered(['Use combo boxes or model bindings for option and theme selection.', 'Use UNKNOWN for unsupported or not-yet-detected payment types.', 'Keep preserveRatio true unless intentionally distorting artwork.', 'Use TilePane for a compact gallery of many payment options.', 'Set accessibleText in the application when the image conveys payment meaning.', 'Do not expect CSS hooks; it is an ImageView subclass.'])]),
        Chapter('See also', [Bullets(['Demo app: <font face=\'Courier\'>PaymentOptionApp</font>. Run with <font face=\'Courier\'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.PaymentOptionApp</font>.', 'Demo app: <font face=\'Courier\'>PaymentOptionTilesApp</font>. Run with <font face=\'Courier\'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.PaymentOptionTilesApp</font>.', 'Related JavaFX class: ImageView.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
