from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, PageBreak, Para, Property, PropertyTable, Section, Table

G = "pop-over"

MANUAL = Manual(
    control="PopOver",
    package="com.dlsc.gemsfx",
    subtitle="Arrow-decorated popup content with detachable mode",
    abstract='PopOver is GemsFX’s arrow-decorated PopupControl. It positions content around an owner node, draws an arrow path, flips to remain on screen, can detach by dragging and supports fade durations and arrow geometry styling.',
    cover_svg=f"{G}/cover.svg",
    cover_caption='The popover points at its owner with a styled arrow and can be detached into a movable popup.',
    chapters=[
        Chapter('Introduction', [Para('<b>PopOver</b> is a lightweight popup with a custom path background and an arrow pointing to an owner node. It is useful for contextual details, pickers and inspectors.'), Section('Key features'), Bullets(['Preferred and computed arrow locations.', 'Screen fitting and side flipping when the preferred side is unavailable.', 'Arrow size, indent and corner-radius properties exposed to CSS.', 'Optional detachable mode by dragging more than 20 pixels.', 'Fade-in and fade-out animations.', 'CalendarPopOver subclass for single-date or date-range selection.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="GemsFX controls live in module <font face='Courier'>com.dlsc.gemsfx</font>.")]),
        Chapter('Getting started', [Code('Label content = new Label("More details");\ncontent.setPrefSize(240, 120);\n\nPopOver popOver = new PopOver(content);\npopOver.setArrowLocation(PopOver.ArrowLocation.TOP_CENTER);\n\nButton owner = new Button("Show");\nowner.setOnAction(evt -> popOver.show(owner));', caption='A minimal popover attached to a button.'), Figure(f"{G}/cover.svg", 'The popover is positioned relative to an owner node.')]),
        Chapter('Anatomy', [Figure(f"{G}/anatomy.svg", 'The parts of the PopOver skin.'), Table(['Part', 'Style class', 'Description'], [['.popover', 'Root style class copied to the root StackPane.'], [':detached', 'Pseudo class active while detached.'], ['.background', 'Path filled with control-inner background and drop shadow.'], ['.border', 'Path used for the border stroke.'], ['.content', 'BorderPane that hosts contentNode.'], ['.calendar-popover', 'Extra style class used by CalendarPopOver.']])]),
        Chapter('Control API', [PropertyTable([Property('contentNode','ObjectProperty&lt;Node&gt;','Label("Content")','Node displayed in the popover; null is rejected.'), Property('detachable','BooleanProperty','false','Allows dragging the popup away from its owner.'), Property('detached','BooleanProperty','false','True after detach; hides the arrow and disables auto-hide.'), Property('arrowSize','DoubleProperty','10','Arrow size. Styleable as -fx-arrow-size.'), Property('arrowIndent','DoubleProperty','12','Distance from arrow to rounded corner. Styleable as -fx-arrow-indent.'), Property('cornerRadius','DoubleProperty','6','Rounded-corner radius. Styleable as -fx-corner-radius.'), Property('arrowLocation','ObjectProperty&lt;ArrowLocation&gt;','TOP_CENTER','Preferred arrow location.'), Property('computedArrowLocation','ReadOnlyObjectProperty&lt;ArrowLocation&gt;','TOP_LEFT initially','Effective location after fitting/flipping on screen.'), Property('fadeInDuration / fadeOutDuration','ObjectProperty&lt;Duration&gt;','100 ms / 100 ms','Durations used by show/hide when animated.'), Property('animated','BooleanProperty','true','Enables fade-in and fade-out animations.')])]),
        Chapter('Arrow geometry', [Para('The skin builds one rounded path and inserts arrow path elements on the computed edge. The minimum size is bound to 2 * cornerRadius + 2 * arrowIndent + 2 * arrowSize.'), Figure(f"{G}/geometry.svg", 'Arrow size, indent and corner radius.')]),
        Chapter('Showing and screen fitting', [Para('show(owner) uses the owner bounds in screen coordinates and the default positive offset 4, which slightly overlaps the owner. show(owner, bounds, offset) accepts explicit bounds and offset. The preferred arrow location is never modified; computedArrowLocation reports the effective fitted location.'), Figure(f"{G}/locations.svg", 'Preferred locations can flip or adjust along the edge to stay on screen.')]),
        Chapter('Detachability and animation', [Figure(f"{G}/detach.svg", 'Dragging a detachable popover away hides the arrow and disables auto-hide.'), Bullets(['setDetachable(true) enables tear-off dragging.', 'Once detached, the :detached pseudo class is active and autoHide is set to false.', 'hide() delegates to hide(fadeOutDuration).', 'setAnimated(false) skips fade transitions.'])]),
        Chapter('Styling', [Table(['Style class / pseudo class', 'Description'], [['.popover', 'Root style class copied to the root StackPane.'], [':detached', 'Pseudo class active while detached.'], ['.background', 'Path filled with control-inner background and drop shadow.'], ['.border', 'Path used for the border stroke.'], ['.content', 'BorderPane that hosts contentNode.'], ['.calendar-popover', 'Extra style class used by CalendarPopOver.']]), Table(['CSS property', 'Type', 'Default'], [['-fx-arrow-size', 'size', '10'], ['-fx-arrow-indent', 'size', '12'], ['-fx-corner-radius', 'size', '6']]), Code('.popover {\n    -fx-arrow-size: 14px;\n    -fx-arrow-indent: 18px;\n    -fx-corner-radius: 10px;\n}\n.popover > .background {\n    -fx-fill: white;\n}', caption='Example PopOver CSS.')]),
        Chapter('Localization', [Table(['Key', 'English default'], [['content.default-label', 'Content']])]),
        Chapter('Recipes', [Section('Calendar popover'), Code('PopOver.CalendarPopOver picker = new PopOver.CalendarPopOver(true);\npicker.show(dateButton);', caption=None), Section('Disable animations'), Code('popOver.setAnimated(false);', caption=None), Section('Allow tear-off'), Code('popOver.setDetachable(true);', caption=None), Section('Checklist'), Numbered(['Choose arrowLocation based on where the popup should appear.', 'Use computedArrowLocation for skin logic, not arrowLocation.', 'Set contentNode before showing.', 'Remember detached popovers no longer auto-hide.'])]),
        Chapter('See also', [PageBreak(), Bullets(["Demo app: <font face='Courier'>PopOverApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.PopOverApp</font>.", 'Related controls: CalendarPicker and DateRangePicker use calendar popovers.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
