"""Content of the SearchField developer manual."""
from manualkit import Bullets, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table
G = "search-field"
MANUAL = Manual(
    control="SearchField", package="com.dlsc.gemsfx", subtitle='Object search with suggestions, auto-completion and optional history', abstract='A generic control that combines a text editor, asynchronous suggestions, auto-completion, object selection and optional search history. The committed result is a domain object, not just the typed string.',
    cover_svg=f"{G}/cover.svg", cover_caption='Generated cartoon overview of SearchField.',
    chapters=[
        Chapter("Introduction", [Para("<b>SearchField</b> A generic control that combines a text editor, asynchronous suggestions, auto-completion, object selection and optional search history. The committed result is a domain object, not just the typed string."), Section("Key features"), Bullets(['Text changes restart a JavaFX Service with a 250 ms delay.', 'ENTER or RIGHT commits the selected item.', 'API and styling details below are verified against the control, skin, CSS and resource bundles.']), Section("Maven dependency"), Code("""<dependency>
    <groupId>com.dlsc.gemsfx</groupId>
    <artifactId>gemsfx</artifactId>
    <version>4.4.1</version>
</dependency>""")]),
        Chapter("Getting started", [Code('SearchField<Country> field = new SearchField<>();\nfield.setSuggestionProvider(request -> countries.stream().filter(c -> c.name().contains(request.getUserText())).toList());\nfield.setConverter(countryConverter);\nfield.setMatcher((country, text) -> country.name().startsWith(text));\nfield.setComparator(Comparator.comparing(Country::name));\nfield.setOnCommit(System.out::println);', caption="A compact setup for SearchField."), Figure(f"{G}/cover.svg", "SearchField in a typical application context.")]),
        Chapter("Anatomy", [Para("The diagram identifies the nodes and state holders created by the implementation."), Figure(f"{G}/anatomy.svg", "The parts of SearchField."), Table(["Topic","Verified source detail"], [["Stylesheet","<font face='Courier'>com/dlsc/gemsfx/search-field.css</font>"],["Root style class","<font face='Courier'>.search-field</font>"],["Graphics","Generated SVGs; no screenshots."]], widths=[30,70])]),
        Chapter("Control API", [Section("Properties and callbacks"), PropertyTable([Property(n,t,d,desc) for n,t,d,desc in [('suggestionProvider', 'ObjectProperty&lt;Callback&lt;SearchFieldSuggestionRequest, Collection&lt;T&gt;&gt;&gt;', 'null', 'Callback used by the background task to find suggestions.'), ('suggestions', 'ObservableList&lt;T&gt;', 'empty, read-only', 'Current unmodifiable suggestion list.'), ('selectedItem', 'ObjectProperty&lt;T&gt;', 'null', 'Currently selected item.'), ('newItemProducer', 'ObjectProperty&lt;Callback&lt;String,T&gt;&gt;', 'null', 'Creates a value when no suggestion matches.'), ('matcher', 'ObjectProperty&lt;BiFunction&lt;T,String,Boolean&gt;&gt;', 'converter text starts with search text', 'Finds the best match.'), ('converter', 'ObjectProperty&lt;StringConverter&lt;T&gt;&gt;', 'item.toString() or empty', 'Turns items into display text.'), ('text / promptText', 'StringProperty', 'empty string', 'Editor text and prompt.'), ('graphic / busyGraphic', 'ObjectProperty&lt;Node&gt;', 'MDI_MAGNIFY / MDI_CACHED', 'Idle and searching graphics.'), ('historyManager', 'ObjectProperty&lt;HistoryManager&lt;String&gt;&gt;', 'null', 'Enables history.'), ('autoCommitOnFocusLost', 'BooleanProperty', 'true', 'Commits on focus lost.'), ('addingItemToHistoryOnEnter / OnFocusLost / OnCommit', 'BooleanProperty', 'true', 'Controls history writes.'), ('onCommit', 'ObjectProperty&lt;Consumer&lt;T&gt;&gt;', 'null', 'Invoked on user commit.')]])]),
        Chapter("Behaviour", [Figure(f"{G}/states.svg", "Important runtime states of SearchField."), Bullets(['Text changes restart a JavaFX Service with a 250 ms delay.', 'ENTER or RIGHT commits the selected item.', 'ESCAPE cancels, clears the field and hides popups.', 'History is disabled while historyManager is null.']), Figure(f"{G}/flow.svg", "How application data flows through SearchField.")]),
        Chapter("Styling", [Figure(f"{G}/styling.svg", "Style hooks for SearchField."), Section("Style classes and pseudo classes"), Table(["Selector / pseudo class","Purpose"], [[f"<font face='Courier'>{s}</font>", "Verified in source, skin or CSS."] for s in ['.search-field', '.auto-completion-label', '.graphic-wrapper', '.history-button', '.search-field-popup', '.search-field-list-view', '.search-field-list-cell .text.middle', ':disabled-popup', ':left-node-visible / :right-node-visible / :no-side-nodes']], widths=[50,50]), Section("Styleable CSS properties"), Table(["CSS property","Type","Default"], [[f"<font face='Courier'>{p}</font>",t,d] for p,t,d in [('-fx-hide-popup-with-single-choice', 'boolean', 'false'), ('-fx-hide-popup-with-no-choice', 'boolean', 'false'), ('-fx-auto-completion-gap', 'size', '1'), ('-fx-show-search-icon', 'boolean', 'true'), ('-fx-auto-commit-on-focus-lost', 'boolean', 'true'), ('-fx-adding-item-to-history-on-enter', 'boolean', 'true'), ('-fx-adding-item-to-history-on-focus-lost', 'boolean', 'true'), ('-fx-adding-item-to-history-on-commit', 'boolean', 'true')]], widths=[48,26,26]) if True else Para("This control declares no additional styleable CSS properties beyond inherited JavaFX properties."), Code(""".search-field {
    /* start with the documented root selector */
}
""")]),
        Chapter("Localization", [Table(["Key","English text"], [[f"<font face='Courier'>{k}</font>",v] for k,v in [('placeholder.history-empty', 'No items.'), ('placeholder.suggestions-empty', 'No items found')]], widths=[45,55]) if True else Para("The verified source does not use ResourceBundleManager for SearchField.")]),
        Chapter("Accessibility", [Para('Sets AccessibleRole.TEXT_FIELD. No automatic accessible text binding is installed.')]),
        Chapter("Recipes", [Section("Programmatic configuration"), Code('SearchField<Country> field = new SearchField<>();\nfield.setSuggestionProvider(request -> countries.stream().filter(c -> c.name().contains(request.getUserText())).toList());\nfield.setConverter(countryConverter);\nfield.setMatcher((country, text) -> country.name().startsWith(text));\nfield.setComparator(Comparator.comparing(Country::name));\nfield.setOnCommit(System.out::println);'), Section("Checklist"), Numbered(["Use the public properties listed in the API chapter.", "Style through documented selectors and CSS properties only.", "Keep application model updates in callbacks such as onClose, onClear or onItemSelected.", "Do not depend on private skin nodes except for documented style selectors."])]),
        Chapter("See also", [Bullets(["Demo application: <font face='Courier'>com.dlsc.gemsfx.demo.SearchFieldApp</font> (run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.SearchFieldApp</font>)", "API documentation: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/"])])
    ])
