from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, PageBreak, Para, Property, PropertyTable, Section, Table

G = "segmented-bar"

MANUAL = Manual(
    control="SegmentedBar",
    package="com.dlsc.gemsfx",
    subtitle="A generic proportional bar for valued segments",
    abstract='SegmentedBar<T extends Segment> displays a list of valued segments as a proportional horizontal or vertical bar. Applications can use the default SegmentView or provide custom factories for typed segment subclasses.',
    cover_svg=f"{G}/cover.svg",
    cover_caption='SegmentedBar lays out generic segments proportionally to their values.',
    chapters=[
        Chapter('Introduction', [Para("<b>SegmentedBar</b> is generic over <font face='Courier'>T extends SegmentedBar.Segment</font>. Each segment has a non-negative value and optional text; the bar computes the total and lays out one node per segment."), Section('Key features'), Bullets(['Generic segment type for domain-specific subclasses.', 'Default SegmentView with label bound to segment.text.', 'Custom segmentViewFactory for typed visuals and tooltips.', 'Horizontal and vertical orientations.', 'Minimum segment size so very small values remain visible.', 'Position style classes for first, middle, last and only segments.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="GemsFX controls live in module <font face='Courier'>com.dlsc.gemsfx</font>.")]),
        Chapter('Getting started', [Code('SegmentedBar<SegmentedBar.Segment> bar = new SegmentedBar<>();\nbar.setOrientation(Orientation.HORIZONTAL);\nbar.getSegments().addAll(\n    new SegmentedBar.Segment(10, "10"),\n    new SegmentedBar.Segment(40, "40"),\n    new SegmentedBar.Segment(50, "50"));', caption='A simple horizontal segmented bar.'), Figure(f"{G}/cover.svg", 'A segmented storage bar with proportional segment widths.')]),
        Chapter('Anatomy', [Figure(f"{G}/anatomy.svg", 'The parts of SegmentedBar and its skin.'), Table(['Style class / pseudo class', 'Description'], [['.segmented-bar', 'Root control style class.'], [':horizontal / :vertical', 'Orientation pseudo classes.'], ['.segment', 'Added by the skin to every segment node.'], ['.segment-view', 'Default SegmentView style class.'], ['.only-segment, .first-segment, .middle-segment, .last-segment', 'Position classes added by the skin.'], ['.segment-view > .label', 'Default label inside SegmentView.']])]),
        Chapter('Control API', [PropertyTable([Property('orientation','ObjectProperty&lt;Orientation&gt;','VERTICAL','HORIZONTAL or VERTICAL. Styleable as -fx-orientation; pseudo classes :horizontal and :vertical.'), Property('minSegmentSize','DoubleProperty','5','Minimum width or height for tiny segments. Styleable as -fx-min-segment-size.'), Property('segmentViewFactory','ObjectProperty&lt;Callback&lt;T, Node&gt;&gt;','SegmentView::new','Creates one node per segment.'), Property('segments','ListProperty&lt;T&gt;','empty list','Segments displayed by the bar.'), Property('total','ReadOnlyDoubleProperty','sum of segment values','Updated when segment values change.')]), Section('Segment model'), PropertyTable([Property('Segment.value','DoubleProperty','constructor value','Must be greater than or equal to zero; negative values throw.'), Property('Segment.text','StringProperty','null','Optional label text used by the default SegmentView.')])]),
        Chapter('Generics and factories', [Figure(f"{G}/generics.svg", 'Use subclasses for domain-specific segment data.'), Para('The demo defines TypeSegment and IssueStatusSegment subclasses. The bar itself only requires value/text, but a custom factory can inspect extra fields and return any Node.'), Code('SegmentedBar<TypeSegment> bar = new SegmentedBar<>();\nbar.setSegmentViewFactory(segment -> new TypeSegmentView(segment));\nbar.getSegments().add(new TypeSegment(14, MediaType.PHOTOS));', caption='Typed segment factory pattern.')]),
        Chapter('Layout algorithm', [Para('The skin divides available width or height by segment.value / total. When a segment would be smaller than minSegmentSize, it receives the minimum and that space is taken from the remaining content size.'), Figure(f"{G}/min-size.svg", 'minSegmentSize keeps tiny values visible.'), Figure(f"{G}/orientation.svg", 'Horizontal and vertical orientations.')]),
        Chapter('Default SegmentView', [Para('The default SegmentView is a StackPane with style class segment-view and one Label. The label text binds to segment.text and is hidden during layout when there is not enough space to show it fully.')]),
        Chapter('Styling', [Table(['Style class / pseudo class', 'Description'], [['.segmented-bar', 'Root control style class.'], [':horizontal / :vertical', 'Orientation pseudo classes.'], ['.segment', 'Added by the skin to every segment node.'], ['.segment-view', 'Default SegmentView style class.'], ['.only-segment, .first-segment, .middle-segment, .last-segment', 'Position classes added by the skin.'], ['.segment-view > .label', 'Default label inside SegmentView.']]), Table(['CSS property', 'Type', 'Default'], [['-fx-orientation', 'Orientation', 'VERTICAL'], ['-fx-min-segment-size', 'size', '5']]), Code('.segmented-bar {\n    -fx-orientation: horizontal;\n    -fx-min-segment-size: 10px;\n}\n.segmented-bar > .segment {\n    -fx-background-color: steelblue;\n}', caption='Example CSS for SegmentedBar.')]),
        Chapter('Localization and accessibility', [Table(['Key', 'English default'], [['accessible.role-description', 'segmented bar']]), Para('The constructor sets AccessibleRole.NODE with the localized role description <i>segmented bar</i>.')]),
        Chapter('Recipes', [Section('Custom colors by type'), Code('bar.setSegmentViewFactory(segment -> {\n    StackPane view = new StackPane(new Label(segment.getText()));\n    view.setStyle("-fx-background-color: " + colorFor(segment.getType()));\n    return view;\n});', caption=None), Section('Bind values'), Code('segment.valueProperty().bind(task.progressProperty().multiply(100));', caption=None), Section('Switch orientation'), Code('bar.setOrientation(Orientation.VERTICAL);', caption=None), Section('Checklist'), Numbered(['Never create segments with negative values.', 'Use subclasses when the view needs more than value/text.', 'Set minSegmentSize for skewed data.', 'Use totalProperty for labels or summaries.'])]),
        Chapter('See also', [PageBreak(), Bullets(["Demo app: <font face='Courier'>SegmentedBarApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.SegmentedBarApp</font>.", 'Related controls: ProgressIndicator-style controls for non-segmented progress.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
