"""Content of the SelectionBox developer manual."""
from manualkit import Bullets, Chapter, Code, Figure, Manual, Numbered, Para, Property, PropertyTable, Section, Table
G = "selection-box"
MANUAL = Manual(
    control="SelectionBox", package="com.dlsc.gemsfx", subtitle='A ComboBox-like picker with single and multiple selection', abstract='A generic Control that opens a popup containing radio buttons in single-selection mode or check boxes in multiple-selection mode. The popup can host top, bottom, left and right decoration nodes.',
    cover_svg=f"{G}/cover.svg", cover_caption='Generated cartoon overview of SelectionBox.',
    chapters=[
        Chapter("Introduction", [Para("<b>SelectionBox</b> A generic Control that opens a popup containing radio buttons in single-selection mode or check boxes in multiple-selection mode. The popup can host top, bottom, left and right decoration nodes."), Section("Key features"), Bullets(['Clicking the control toggles the popup unless disabled or read-only.', 'Single mode uses RadioButton items; multiple mode uses CheckBox items.', 'API and styling details below are verified against the control, skin, CSS and resource bundles.']), Section("Maven dependency"), Code("""<dependency>
    <groupId>com.dlsc.gemsfx</groupId>
    <artifactId>gemsfx</artifactId>
    <version>4.4.1</version>
</dependency>""")]),
        Chapter("Getting started", [Code('SelectionBox<String> box = new SelectionBox<>("One", "Two", "Three");\nbox.setPromptText("Choose items");\nbox.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);\nbox.setSelectedItemsConverter(new SimpleStringConverter<>(items -> items.size() + " selected"));', caption="A compact setup for SelectionBox."), Figure(f"{G}/cover.svg", "SelectionBox in a typical application context.")]),
        Chapter("Anatomy", [Para("The diagram identifies the nodes and state holders created by the implementation."), Figure(f"{G}/anatomy.svg", "The parts of SelectionBox."), Table(["Topic","Verified source detail"], [["Stylesheet","<font face='Courier'>com/dlsc/gemsfx/selection-box.css</font>"],["Root style class","<font face='Courier'>.selection-box</font>"],["Graphics","Generated SVGs; no screenshots."]], widths=[30,70])]),
        Chapter("Control API", [Section("Properties and callbacks"), PropertyTable([Property(n,t,d,desc) for n,t,d,desc in [('items', 'ListProperty&lt;T&gt;', 'empty list', 'Items displayed in the popup.'), ('selectionModel', 'ObjectProperty&lt;MultipleSelectionModel&lt;T&gt;&gt;', 'CustomMultipleSelectionModel', 'Selection state.'), ('currentSelectionMode', 'ReadOnlyObjectProperty&lt;SelectionMode&gt;', 'selection model mode', 'Read-only mode mirror.'), ('top / bottom / left / right', 'ObjectProperty&lt;Node&gt;', 'top has buttons, others null', 'Popup BorderPane decorations.'), ('placeholder', 'ObjectProperty&lt;Node&gt;', 'null', 'Shown when items is empty.'), ('graphic', 'ObjectProperty&lt;Node&gt;', 'null', 'Graphic in display label.'), ('promptText', 'StringProperty', 'null', 'Shown when nothing is selected.'), ('autoHideOnSelection', 'BooleanProperty', 'true', 'Controls hiding after item / extra-button actions.'), ('selectedItemsConverter', 'ObjectProperty&lt;StringConverter&lt;List&lt;T&gt;&gt;&gt;', 'null', 'Formats selected values.'), ('itemConverter', 'ObjectProperty&lt;StringConverter&lt;T&gt;&gt;', 'null', 'Formats popup items.'), ('readOnly', 'BooleanProperty', 'false', 'Disables interaction; styleable.'), ('animationEnabled', 'BooleanProperty', 'false', 'Enables 200 ms fade transitions; styleable.'), ('onShowing/onShown/onHiding/onHidden', 'ObjectProperty&lt;EventHandler&lt;WindowEvent&gt;&gt;', 'null', 'Popup lifecycle handlers.')]])]),
        Chapter("Behaviour", [Figure(f"{G}/states.svg", "Important runtime states of SelectionBox."), Bullets(['Clicking the control toggles the popup unless disabled or read-only.', 'Single mode uses RadioButton items; multiple mode uses CheckBox items.', 'The popup auto-fixes, auto-hides and hides on ESCAPE.', 'show() and hide() communicate with the skin via the showPopup marker.', 'If animationEnabled is true, popup opacity fades over 200 ms.']), Figure(f"{G}/flow.svg", "How application data flows through SelectionBox.")]),
        Chapter("Styling", [Figure(f"{G}/styling.svg", "Style hooks for SelectionBox."), Section("Style classes and pseudo classes"), Table(["Selector / pseudo class","Purpose"], [[f"<font face='Courier'>{s}</font>", "Verified in source, skin or CSS."] for s in ['.selection-box', '.display-label', '.arrow-button', '.arrow', '.selection-popup > .content', '.extra-buttons-box .extra-button', '.options-scroll-pane .radio-button', '.options-scroll-pane .check-box', ':showing', ':empty', ':single', ':multiple', ':readonly']], widths=[50,50]), Section("Styleable CSS properties"), Table(["CSS property","Type","Default"], [[f"<font face='Courier'>{p}</font>",t,d] for p,t,d in [('-fx-read-only', 'boolean', 'false'), ('-fx-animation-enabled', 'boolean', 'false')]], widths=[48,26,26]) if True else Para("This control declares no additional styleable CSS properties beyond inherited JavaFX properties."), Code(""".selection-box {
    /* start with the documented root selector */
}
""")]),
        Chapter("Localization", [Table(["Key","English text"], [[f"<font face='Courier'>{k}</font>",v] for k,v in [('action.clear', 'Clear'), ('action.select-all', 'Select All')]], widths=[45,55]) if True else Para("The verified source does not use ResourceBundleManager for SelectionBox.")]),
        Chapter("Accessibility", [Para('Sets AccessibleRole.COMBO_BOX and binds accessible text to the current selection.')]),
        Chapter("Recipes", [Section("Programmatic configuration"), Code('SelectionBox<String> box = new SelectionBox<>("One", "Two", "Three");\nbox.setPromptText("Choose items");\nbox.getSelectionModel().setSelectionMode(SelectionMode.MULTIPLE);\nbox.setSelectedItemsConverter(new SimpleStringConverter<>(items -> items.size() + " selected"));'), Section("Checklist"), Numbered(["Use the public properties listed in the API chapter.", "Style through documented selectors and CSS properties only.", "Keep application model updates in callbacks such as onClose, onClear or onItemSelected.", "Do not depend on private skin nodes except for documented style selectors."])]),
        Chapter("See also", [Bullets(["Demo application: <font face='Courier'>com.dlsc.gemsfx.demo.SelectionBoxApp</font> (run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.SelectionBoxApp</font>)", "API documentation: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/"])])
    ])
