from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, PageBreak, Para, Property, PropertyTable, Section, Table

G = "simple-filter-view"

MANUAL = Manual(
    control="SimpleFilterView",
    package="com.dlsc.gemsfx",
    subtitle="A lightweight HBox filter builder with removable chips",
    abstract='SimpleFilterView is a lightweight HBox helper that creates common filter input controls and mirrors their selected values as ChipView objects. It does not filter data itself; applications consume its controls and onChange callback.',
    cover_svg=f"{G}/cover.svg",
    cover_caption="SimpleFilterView arranges compact filter inputs and exposes their values as chips.",
    chapters=[
        Chapter('Introduction', [Para("<b>SimpleFilterView</b> extends <font face='Courier'>HBox</font>. It is not skinned and does not own a predicate pipeline. Instead, it provides factory methods for common input controls and a chips list suitable for <font face='Courier'>ChipsViewContainer</font>."), Section('Key features'), Bullets(['Factory methods for SelectionBox, CheckBox, text fields, search fields, DateRangePicker, CalendarPicker and DatePicker.', 'STANDARD and COMPACT layout modes.', 'Automatic selection-item, first, middle, last and only style classes on child controls.', 'Read-only chips list with close actions that clear the source control.', 'clear() resets supported controls and invokes onChange once.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="The class is in <font face='Courier'>com.dlsc.gemsfx</font>.")]),
        Chapter('Getting started', [Code('SimpleFilterView filters = new SimpleFilterView();\nSelectionBox<Status> status = filters.addSelectionBox("Status", Status.class);\nDateRangePicker range = filters.addDateRangePicker("Date Range");\nCustomTextField search = filters.addSearchTextField("Search");\n\nChipsViewContainer chips = new ChipsViewContainer();\nchips.chipsProperty().bind(filters.chipsProperty());\nchips.setOnClear(filters::clear);\n\nfilters.setOnChange(() -> reload(status.getSelectionModel().getSelectedItems(),\n                                 range.getValue(), search.getText()));', caption='A SimpleFilterView with chips and a reload callback.'), Figure(f"{G}/cover.svg", 'SimpleFilterView with standard controls, compact controls and bound chips.')]),
        Chapter('Anatomy', [Figure(f"{G}/anatomy.svg", 'The parts of SimpleFilterView.'), Table(['Part', 'Description'], [['HBox root', 'The control itself; style class simple-filter-view.'], ['Factory-created children', 'Supported JavaFX and GemsFX inputs.'], ['selection-item classes', 'Child style classes for first, middle, last or only.'], ['chips property', 'Read-only chips generated from selected or entered values.'], ['onChange', 'Application callback after value changes.']])]),
        Chapter('Control API', [PropertyTable([Property('layoutMode', 'ObjectProperty&lt;LayoutMode&gt;', 'STANDARD', 'STANDARD or COMPACT. COMPACT activates the :compact pseudo class.'), Property('chips', 'ReadOnlyListProperty&lt;ChipView&lt;?&gt;&gt;', 'empty list', 'Chips representing selected or entered values.'), Property('onChange', 'ObjectProperty&lt;Runnable&gt;', 'null', 'Called after supported child controls change; clear() calls it once at the end.')], caption=None), Section('Factory methods'), Table(['Method', 'Result'], [['addSelectionBox(String, Class&lt;Enum&gt;)', 'SelectionBox with enum values and converter.'], ['addSelectionBox(String, Collection) / varargs', 'SelectionBox for supplied values.'], ['addCheckBox(String)', 'CheckBox.'], ['addTextField(String)', 'CustomTextField.'], ['addSearchTextField(String)', 'SearchTextField.'], ['addDateRangePicker(String)', 'DateRangePicker with value null, no preset title and no icon.'], ['addCalendarPicker(String)', 'Non-editable CalendarPicker with value null.'], ['addDatePicker(String)', 'Non-editable DatePicker with value null.']])]),
        Chapter('Layout modes', [Para("STANDARD keeps normal spacing. COMPACT activates the <font face='Courier'>:compact</font> pseudo class and the CSS removes gaps so adjacent filter inputs look like one segmented bar."), Figure(f"{G}/modes.svg", 'STANDARD and COMPACT layout modes.')]),
        Chapter('Chips and clear behaviour', [Para('Each supported control contributes chips for its selected or entered values. Closing a chip clears the originating value.'), Figure(f"{G}/chips.svg", 'Values flow from controls into the chips list.'), Figure(f"{G}/clear-flow.svg", 'clear() resets supported controls and calls onChange once.'), Callout('If clear() encounters an unsupported child node type it throws IllegalStateException. Add custom controls only when your application handles clearing them separately.', kind='warning')]),
        Chapter('Using values in an application', [Para('SimpleFilterView deliberately stops at input collection. The application owns the actual filtering logic and can read the created controls directly inside the onChange callback.'), Code('SimpleFilterView filters = new SimpleFilterView();\nSelectionBox<Status> status = filters.addSelectionBox("Status", Status.class);\nCustomTextField search = filters.addSearchTextField("Search");\nCheckBox archived = filters.addCheckBox("Archived");\n\nfilters.setOnChange(() -> {\n    List<Status> statuses = status.getSelectionModel().getSelectedItems();\n    String text = search.getText();\n    boolean includeArchived = archived.isSelected();\n    service.reload(statuses, text, includeArchived);\n});', caption='Read the factory-created controls when the filter state changes.'), Bullets(['Keep references to the controls returned by the factory methods.', 'Debounce expensive back-end calls in your application service if needed.', 'Use the chips list for display and clearing; do not parse chip text as application state.', 'Call clear() when a saved search or reset button should restore the default state.'])]),
        Chapter('Styling', [Table(['Style class / pseudo class', 'Description'], [['.simple-filter-view', 'Root HBox.'], [':compact', 'Active when layoutMode is COMPACT.'], ['.selection-item', 'Added to child Regions.'], ['.first, .middle, .last, .only', 'Position classes for grouped controls.'], ['.check-box', 'Regular JavaFX CheckBox styling hook.']]), Para('SimpleFilterView has no styleable CSS properties.'), Code('.simple-filter-view:compact .selection-item {\n    -fx-background-radius: 0;\n}\n.simple-filter-view .selection-item.only {\n    -fx-background-radius: 6px;\n}', caption='Example CSS for compact grouping.')]),
        Chapter('Localization', [Para("The control uses ResourceBundleManager only for accessibility. The key <font face='Courier'>accessible.role-description</font> has the English default <i>filter</i>.")]),
        Chapter('Accessibility', [Para("SimpleFilterView sets <font face='Courier'>AccessibleRole.NODE</font> and uses the localized role description <i>filter</i>. The child controls keep their own accessible roles.")]),
        Chapter('Recipes', [Section('Use compact mode'), Code('filters.setLayoutMode(SimpleFilterView.LayoutMode.COMPACT);', caption=None), Section('Bind chips to a container'), Code('chips.chipsProperty().bind(filters.chipsProperty());\nchips.setOnClear(filters::clear);', caption=None), Section('Single-selection enum'), Code('SelectionBox<Status> status = filters.addSelectionBox("Status", Status.class);\nstatus.getSelectionModel().setSelectionMode(SelectionMode.SINGLE);', caption=None), Section('Reload after change'), Code('filters.setOnChange(this::reloadResults);', caption=None), Section('Checklist'), Numbered(['Use SimpleFilterView for inputs, not automatic data filtering.', 'Use FilterView when predicates and filteredItems are required.', 'Bind chips to a ChipsViewContainer for a clear-all UI.', 'Avoid unsupported custom children unless you handle their clear behaviour.'])]),
        Chapter('See also', [PageBreak(), Bullets(["Demo app: <font face='Courier'>SimpleFilterViewApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.SimpleFilterViewApp</font>.", 'Related controls: FilterView, ChipsViewContainer, SelectionBox, DateRangePicker and CalendarPicker.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
