from manualkit import Bullets, Callout, Chapter, Code, Figure, Manual, Numbered, PageBreak, Para, Property, PropertyTable, Section, Table

G = "text-view"

MANUAL = Manual(
    control="TextView",
    package="com.dlsc.gemsfx",
    subtitle="Selectable multiline text with copy support",
    abstract='TextView displays multiline text in a selectable TextFlow. Users can drag, double-click words, triple-click paragraphs, copy selection or all text, and customize highlight paints through CSS.',
    cover_svg=f"{G}/cover.svg",
    cover_caption='TextView renders selectable text with a highlight path and clipboard actions.',
    chapters=[
        Chapter('Introduction', [Para('<b>TextView</b> is a Control for read-only selectable text. It differs from TextArea by rendering text through a TextFlow and exposing copy operations without editing.'), Section('Key features'), Bullets(['Drag selection across multiline text.', 'Double-click selects a word and triple-click selects a paragraph unless disabled.', 'Shortcut+C copies selected text; Shortcut+A selects all; Backspace clears selection.', 'Context menu offers Copy All and Copy Selection.', 'Read-only selectedText property.', 'CSS properties for highlight fill, stroke and selected text fill.']), Section('Maven dependency'), Code('<dependency>\n    <groupId>com.dlsc.gemsfx</groupId>\n    <artifactId>gemsfx</artifactId>\n    <version>4.4.1</version>\n</dependency>', caption="GemsFX controls live in module <font face='Courier'>com.dlsc.gemsfx</font>.")]),
        Chapter('Getting started', [Code('TextView textView = new TextView();\ntextView.setText(longReadOnlyText);\n\nLabel selected = new Label();\nselected.textProperty().bind(textView.selectedTextProperty());\n\nButton copyAll = new Button("Copy all");\ncopyAll.setOnAction(evt -> textView.copyAll());', caption='Display selectable text and observe the selected text.'), Figure(f"{G}/cover.svg", 'TextView displays selectable text in a TextFlow.')]),
        Chapter('Anatomy', [Figure(f"{G}/anatomy.svg", 'The TextView skin uses a TextFlow, Text and highlight Path.'), Table(['Part', 'Style class', 'Description'], [['.text-view', 'Root control style class.'], [':focused', 'Changes highlight fill/text fill in text-view.css.'], ['.selectable-text', 'TextFlow used by the skin.'], ['.text', 'Text node inside the TextFlow.']])]),
        Chapter('Control API', [PropertyTable([Property('text','StringProperty','null','Multiline text displayed by the skin Text node.'), Property('selectedText','ReadOnlyStringProperty','null','Updated from the skin when selection changes.'), Property('disableTextSelectionByMouseClicks','BooleanProperty','false','Disables double-click word and triple-click paragraph selection, but not dragging.'), Property('highlightFill','ObjectProperty&lt;Paint&gt;','Color.BLUE; UA stylesheet derives background','Selection background paint. Styleable as -fx-highlight-fill.'), Property('highlightStroke','ObjectProperty&lt;Paint&gt;','Color.TRANSPARENT','Selection outline paint. Styleable as -fx-highlight-stroke.'), Property('highlightTextFill','ObjectProperty&lt;Paint&gt;','Color.WHITE; UA stylesheet also sets focused white','Selected text fill. Styleable as -fx-highlight-text-fill.')])]),
        Chapter('Selection behaviour', [Figure(f"{G}/selection.svg", 'Mouse selection and keyboard copy behaviour.'), Bullets(['Primary-button drag selects a character range.', 'Double-click selects an alphanumeric word.', 'Triple-click selects a paragraph up to newline boundaries.', 'Selection is removed when size changes or focus is lost while no context menu is open.'])]),
        Chapter('Clipboard and context menu', [Figure(f"{G}/clipboard.svg", 'Copy APIs and context-menu items.'), Para('copySelection() and copyAll() are intentionally non-final so applications can override copying behaviour. The context menu is created lazily on first context-menu request and uses localized menu text.')]),
        Chapter('Styling', [Figure(f"{G}/styling.svg", 'Highlight paints can be customized with CSS.'), Table(['Style class / pseudo class', 'Description'], [['.text-view', 'Root control style class.'], [':focused', 'Changes highlight fill/text fill in text-view.css.'], ['.selectable-text', 'TextFlow used by the skin.'], ['.text', 'Text node inside the TextFlow.']]), Table(['CSS property', 'Type', 'Default'], [['-fx-highlight-fill', 'Paint', 'Java default blue; UA default derive(-fx-control-inner-background, -20%)'], ['-fx-highlight-stroke', 'Paint', 'transparent'], ['-fx-highlight-text-fill', 'Paint', 'Java default white; UA default -fx-text-inner-color / focused white']]), Code('.text-view {\n    -fx-highlight-fill: rgba(80, 120, 255, .35);\n    -fx-highlight-stroke: #506cff;\n    -fx-highlight-text-fill: black;\n}', caption='Example TextView CSS.')]),
        Chapter('Localization', [Table(['Key', 'English default'], [['context.copy-selection', 'Copy Selection'], ['context.copy-all', 'Copy All']])]),
        Chapter('Accessibility', [Para("TextView sets <font face='Courier'>AccessibleRole.TEXT</font> and binds accessible text to the text property through AccessibilityUtil. Application-set accessible text takes precedence according to the helper behaviour.")]),
        Chapter('Recipes', [Section('Disable click selection shortcuts'), Code('textView.setDisableTextSelectionByMouseClicks(true);', caption=None), Section('Override copy'), Code('TextView view = new TextView() {\n    @Override public void copySelection() {\n        audit(getSelectedText());\n        super.copySelection();\n    }\n};', caption=None), Section('Use inside a ScrollPane'), Code('ScrollPane scroll = new ScrollPane(textView);\nscroll.setFitToWidth(true);', caption=None), Section('Checklist'), Numbered(['Use TextView for read-only selectable text, not editing.', 'Bind selectedText when the application needs live selection state.', 'Style highlight paints for sufficient contrast.', 'Keep focus behaviour in mind when embedding in complex panes.'])]),
        Chapter('See also', [PageBreak(), Bullets(["Demo app: <font face='Courier'>TextViewApp</font>. Run with <font face='Courier'>mvn javafx:run -f gemsfx-demo/pom.xml -Dmain.class=com.dlsc.gemsfx.demo.TextViewApp</font>.", 'Related control: EnhancedLabel for whole-label copy selection.', 'API docs: https://dlsc-software-consulting-gmbh.github.io/GemsFX/api/'])])
    ]
)
