label.to=TO
button.cancel=CANCEL
button.apply=APPLY
section.presets.title=QUICK SELECT
preset.today=Today
preset.yesterday=Yesterday
preset.this-week=This Week
preset.this-month=This Month
preset.last-month=Last Month
