message.no-items=No items
message.single-item=Showing the only item.
message.showing-all-items=Showing all {0} items.
message.showing-range=Showing items {0} to {1} of {2}.
label.results-per-page=Results per page
button.first-page=First
button.last-page=Last
button.previous-page=Previous
button.next-page=Next
